python/fledge/services/core/api/plugins/remove.py
Signed-off-by: rajeshkumar426 <rajeshkumar426@outlook.com>
when plugin packages gets removed successfully via API, then clear cache to get latest available plugin list.
**note..** We have no control if purge / removal action taken directly on the system. then cache will refresh after configured time only i.e. be default 15 mins
=> FOGL- 3718 FOGL-3775 Clear available packages cache on package removal via API

C/plugins/common/include/omf.h, C/plugins/common/omf.cpp, tests/unit/C/plugins/common/test_omf_translation.cpp
Tests
assets:
```
curl  -s -S  -i -X POST http://localhost:${storage_port}/storage/reading  -d  @- << EOF
{
"readings" : [
{ "user_ts" : "2020-03-05 10:01:01",           "asset_code": "3814_asset1",  "reading" : {"sinusoid1":100}},
{ "user_ts" : "2020-03-05 10:02:01",           "asset_code": "3814_asset2",  "reading" : {"sinusoid2":200}},
{ "user_ts" : "2020-03-05 10:02:01",           "asset_code": "3814_asset3",  "reading" : {"sinusoid3":300}},
{ "user_ts" : "2020-03-05 10:02:01",           "asset_code": "3814_asset4",  "reading" : {"sinusoid4":400}},
{ "user_ts" : "2020-03-05 10:02:01",           "asset_code": "3814_asset4_1",  "reading" : {"sinusoid4_1":400}},
{ "user_ts" : "2020-03-05 10:02:01",           "asset_code": "3814_asset5", …
```
=> Fogl 3814: Implement the 'Name Map' functionality as outlined in the Google document 'Hierarchies, PI Server and FogLAMP'

C/tasks/north/sending_process/sending_process.cpp
data not sent:
```
{
"track": [
{
"asset": "sinusoid",
"event": "Ingest",
"service": "sinusoid1",
"fledge": "Fledge",
"plugin": "sinusoid",
"timestamp": "2020-03-12 15:43:51.729"
}
]
}
{
"uptime": 62,
"dataRead": 2,
"dataSent": 0,
"dataPurged": 0,
"authenticationOptional": true,
"serviceName": "Fledge",
"hostName": "ihsdev",
"ipAddresses": [
"192.168.1.50"
],
"health": "green",
"safeMode": false
}
```
data sent:
```
{
"track": [
{
"asset": "sinusoid",
"event": "Ingest",
"service": "sinusoid1",
"fledge": "Fledge",
"plugin": "sinusoid",
"timestamp": "2020-03-12 15:47:28.007"
},
{
"asset": "sinusoid",
"event": "Egress",
"service": "North_Readings_to_PI",
"fledge": "Fledge",
"plugin": "PI_Server_V2",
"timestamp": "2020-03-12 15:47:30.097"
}
]
}
{ …
```
=> FOGL-3283: asset tracker updated on sent not on load

tests/unit/python/fledge/common/test_configuration_manager.py
Configuration unit tests improved.
I have run this in **n** number of iterations and couldn't see any issue on all platforms. Also No regression has been introduced by the change as it passes on CI platforms as well (i.e custom JOB)
```
#!/usr/bin/env bash
ITERATIONS=10
for i in $(seq ${ITERATIONS}); do
echo "***************"
echo "***************"
echo "Run $i"
echo "***************"
echo "***************"
python3 -m pytest -s -vv ${FLEDGE_ROOT}/tests/unit/python/fledge/common/test_configuration_manager.py
if [ $? -ne 0 ]
then
exit 1
fi
done
```
**NOTE** - It has nothing specifically to do with white-labelled code base.
=> FOGL-3859 asyncio issue fixes & unused code removal of configuration unit tests

python/fledge/tasks/north/sending_process.py, tests/unit/python/fledge/tasks/north/test_sending_process.py
**Before:** - Http north python plugin is always sending with timestamp ends with **+00**
```
[{'readings': {'sinusoid': 0.0}, 'asset': 'sinusoid', 'timestamp': '2020-03-30 11:23:30.943848+00'}, {'readings': {'sinusoid': 0.104528463}, 'asset': 'sinusoid', 'timestamp': '2020-03-30 11:23:31.943831+00'}, {'readings': {'sinusoid': 0.207911691}, 'asset': 'sinusoid', 'timestamp': '2020-03-30 11:23:32.943834+00'}, {'readings': {'sinusoid': 0.309016994}, 'asset': 'sinusoid', 'timestamp': '2020-03-30 11:23:33.943837+00'}, {'readings': {'sinusoid': 0.406736643}, 'asset': 'sinusoid', 'timestamp': '2020-03-30 11:23:34.943831+00'}]#012NoneType: None
```
And with HTTP-north C-Plugin it always sends with **Zulu** timestamp Z
```
[{"timestamp":"2020-03-30T11:02:24.185683Z","asset":"sinusoid","readings":{" …
```
=> FOGL-3867 - UTC Zulu time added in python sending process

scripts/package/debian/package_update.sh, scripts/package/debian/upgrade/1.8.sh, scripts/plugins/storage/sqlite/downgrade/33.sql, scripts/plugins/storage/sqlite/upgrade/34.sql
1) Sql queries and also added detailed comments for what purpose the queries meant to be
Also fixed new config items payload values
2) Asset_tracker plugin entry added
3) Package upgrade changes - Assuming that new version is **1.8** because upgrade script to be added with same name (i.e in our case 1.8sh)
a) Removed C-source binaries from existing system (PI_SERVER_V2, ops_V2) so that plugin discovery will not show these with new upgraded version
b) Syntactical error fixes in package_update.sh
**NOTE** - With the changes 
a) I am able to run foglamp upgrade successfully with both installations package vs non-package installation with default endpoint settings of North task (i.e connection relay)
b) But definitely it has some permutations & combination to test with on …
=> FOGL-3905 - upgrade fixes

tests/system/python/api/test_plugin_discovery.py, tests/system/python/conftest.py, tests/system/python/packages/test_available_and_install_api.py
System API tests - Default 3 North plugins
System Package tests - Default Counter value changed to 3 as now we have 3 by default plugins
System E2E tests - Fixed Service Port typecast as configuration needs every item into string
**NOTE** - I ran custom Jobs on ub1804 nightly & ub1804 Package installation custom Job and these JOBS are back to normal with the change
=> FOGL-3914 - System tests fixes as per FOGL-3869

scripts/fledge
Value is retrieved for --name arg of C Tasks in fledge status
**Output**
```
$ ./scripts/fledge status
Fledge v1.7.0 running.
Fledge Uptime:  35 seconds.
Fledge records: 4838 read, 5 sent, 0 purged.
fledge.services.storage --address=0.0.0.0 --port=35519
fledge.services.south --port=35519 --address=127.0.0.1 --name=Sine
=== Fledge tasks:
fledge.tasks.north.sending_process --port=35519 --address=127.0.0.1 --name=HTP
tasks/sending_process --port=35519 --address=127.0.0.1 --name=HTC
```
=> FOGL-3915 name info is added for C tasks in fledge status script

C/common/reading_set.cpp
=> FOGL-3956: Handle Uint as 64 bits in reading_set

scripts/fledge
**O/P**
It has South services (both plugins language) | C tasks (both python & C version) | Notification service
```
$ ./scripts/fledge status
Fledge v1.7.0 running.
Fledge Uptime:  41 seconds.
Fledge records: 10060 read, 954 sent, 0 purged.
fledge.services.storage --address=0.0.0.0 --port=41561
fledge.services.south --port=41561 --address=127.0.0.1 --name=Bench 
fledge.services.south --port=41561 --address=127.0.0.1 --name=Sine #1 
fledge.services.south --port=41561 --address=127.0.0.1 --name=S I N E 
fledge.services.south --port=41561 --address=127.0.0.1 --name=Rand C 
fledge.services.south --port=41561 --address=127.0.0.1 --name=Fledge Bench …
```
=> FOGL-3991 fledge status output fixes

python/fledge/services/core/api/plugins/common.py
**Logs**
```
Apr 30 11:52:26 aj Fledge S I N E[17333] INFO: sinusoid: fledge.plugins.south.sinusoid: Sinusoid plugin_init: called
Apr 30 11:54:02 aj Fledge HTTP South #1[17337] INFO: http_south: fledge.plugins.south.http_south: South HTTP plugin shut down.
Apr 30 11:55:55 aj Fledge Ht #1[18938] ERROR: http_north: fledge.plugins.north.http_north: Server error code: 500, reason: Internal Server Error
Apr 30 12:16:25 aj Fledge Env[13750] INFO: envirophat: fledge.plugins.south.envirophat: Old config for Enviro pHAT plugin {'plugin': {'description': 'Enviro pHAT Poll Plugin', 'type': 'string', 'value': 'envirophat', 'default': 'envirophat'}, 'assetNamePrefix': {'description': ........
```
=> FOGL-3980 module name fixes for loading python plugin

scripts/services/storage
1) indentation & style fixes (square brackets [[ ]] )
2) common write_log bash logger used for logging in case of FLEDGE_ROOT is set
**O/P**
New log
```
Apr 29 17:22:35 aj Fledge [31919] INFO: scripts.services.storage: Fledge storage microservice found in FLEDGE_ROOT location: /home/Development/fledge
```
Previously it was without Fledge Prefix & PID. Below is the old log
```
Apr 28 08:18:55 aj pi: Fledge storage microservice found in FLEDGE_ROOT location: /home/pi/fledge
```
=> FOGL-4000 common bash logger script used for scripts.services.storage

python/fledge/services/core/support.py
**Support extract file structure**
```
drwxrwxr-x  2 foglamp foglamp    4096 Apr 29 12:45 package_logs
-rw-rw-r--  1 foglamp foglamp   25649 Apr 30 15:13 syslogStorage-200430-15-13-48
-rw-rw-r--  1 foglamp foglamp    3572 Apr 30 15:13 syslog-S-I-N-E-200430-15-13-48
-rw-rw-r--  1 foglamp foglamp    3571 Apr 30 15:13 syslog-Sine-#1-200430-15-13-48
-rw-rw-r--  1 foglamp foglamp    5831 Apr 30 15:13 syslog-Rand-C-200430-15-13-48
-rw-rw-r--  1 foglamp foglamp    4884 Apr 30 15:13 syslog-PI-Serv-Py-200430-15-13-48
-rw-rw-r--  1 foglamp foglamp    3099 Apr 30 15:13 syslog-Pi-#1-200430-15-13-48
-rw-rw-r--  1 foglamp foglamp   20391 Apr 30 15:13 syslog-O-M-F-200430-15-13-48
-rw-rw-r--  1 foglamp foglamp   18029 Apr 30 15:13 …
```
=> FOGL-3999 grep cmd improved as per Fledge Prefix for fetching logs in support bundle & other code refactoring

python/fledge/services/core/api/statistics.py, python/fledge/services/core/routes.py, tests/unit/python/fledge/services/core/api/test_statistics_api.py
**DB results**
```
$ sqlite3 data/fledge.db 
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> .headers on
sqlite> select key, 4 * (sum(value) / count(value)) from statistics_history where history_ts >= datetime('now', '-5 Minute') and key in ("RANDOM1", "FASTSINUSOID", "READINGS", "SINUSOID" ) group by key;
key|4 * (sum(value) / count(value))
FASTSINUSOID|120
RANDOM1|60
READINGS|240
SINUSOID|60
sqlite> 
sqlite> select key, 4 * (sum(value) / count(value)) from statistics_history where history_ts >= datetime('now', '-15 Minute') and key in ("RANDOM1", "FASTSINUSOID", "READINGS", "SINUSOID" ) group by key;
key|4 * (sum(value) / count(value))
FASTSINUSOID|120
RANDOM1|60
READINGS|240
SINUSOID|60
```
**curl …
=> FOGL-4068 API to retrieve statistics rates

tests/system/lab/reset, tests/system/lab/run, tests/system/lab/test, tests/system/lab/test.config
7. RPi -  postgres
8. RPi -  sqlitememory
note- Raspberry Pi with sqlite was already covered. 
We already allow storage engine in conftest for system test using pytest, so we can setup CI jobs with that param to run for postgres (across the platforms).
For sqlite in memeory we need to modify conftest. I will raise a JIRA for that; Also we will start to run test for CSV playback (vibration demo) using  sqlite in memeory.
=> FOGL-4057 test on RPi with postgres and sqlite-in-memory

CONTRIBUTING.md, python/fledge/services/core/api/south.py
The version of zeroconf used previously stops currently announcing services after a short period. This prevents services running outside the machine, e.g. ESP8266 service, to find services other than during a short window after fledge is start.
Also the fledge/south API gives an internal error if a service outside of the machine is registered with the core.
=> FOGL-4122 Update zeroconf library and allow south services on remote machines

C/services/storage/storage.cpp
failure as the Advanced configuration category does not exist
=> FOGL-4076-fix When Fledge is started with a blank database there is a

python/fledge/services/core/service_registry/service_registry.py
due to too strict checks in the service registry
=> FOGL-4134 Failed external services can not register when they restart

.gitignore, python/fledge/services/core/api/repos/configure.py, python/fledge/services/core/routes.py
**Assumption**
1)There is no existing setup for currently.
2) Non Package installation (i.e sudo make install) - manual install of FL via sudo will work
3) WL code available [here](http://archives.dianomic.com/foglamp/fixes/FOGL-4133/ubuntu1804/x86_64/sources.tar.gz)
**How to test?**
```
$ curl -sX POST localhost:8081/foglamp/repository -d '{"url": "http://archives.fledge-iot.org", "version": "nightly"}'
$ curl -sX POST localhost:8081/foglamp/repository -d '{"url": "http://archives.dianomic.com/foglamp", "version": "fixes/FOGL-4133"}'
```
**Pending**
1) RPM Platform - Raise JIRA FOGL-4176
=> FOGL-4133 POST repository API endpoint added for debian systems

python/fledge/services/core/api/scheduler.py, python/fledge/services/core/api/service.py, python/fledge/services/core/routes.py, tests/unit/python/fledge/services/core/api/test_service.py
=> FOGL-4264 - extend service API for management type

python/fledge/services/core/api/plugins/discovery.py, tests/unit/python/fledge/services/core/api/plugins/test_discovery.py
@MarkRiddoch fyi, We would also want to see all available packages. 
At the moment we have restricted with supported types
a) For plugins: `http://localhost:8081/fledge/plugins/available?type=` | `'north', 'south', 'filter', 'notify', 'rule'` 
b) For service package we have separate endpoint `http://localhost:8081/fledge/service/available`
We may add new endpoint and get it via `curl -sX GET http://localhost:8081/fledge/packages/available`
=> FOGL-4233 plugin available packages with 'north', 'south', 'filter', 'notify', 'rule' types only

python/fledge/services/core/api/south.py
```
// http://localhost:8081/foglamp/south?cached=false
{
"services": [
{
"name": "sinusoid",
"address": "",
"management_port": "",
"service_port": "",
"protocol": "",
"status": "",
"assets": [
],
"plugin": {
"name": "",
"version": ""
},
"schedule_enabled": "unknown"
}
]
}
```
=> FOGL-4444 Out of index range fixes in south API when schedule entry is missing for matching South child category

python/fledge/common/plugin_discovery.py, python/fledge/services/core/api/plugins/common.py, python/fledge/services/core/api/plugins/discovery.py, python/fledge/services/core/api/plugins/install.py, python/fledge/services/core/api/plugins/remove.py, python/fledge/services/core/api/plugins/update.py, tests/system/python/api/test_plugin_discovery.py, tests/system/python/plugin_and_service.py, tests/system/python/scripts/install_c_plugin, tests/system/python/scripts/reset_plugins, tests/unit/python/fledge/common/test_plugin_discovery.py, tests/unit/python/fledge/services/core/api/plugins/test_discovery.py, tests/unit/python/fledge/services/core/api/plugins/test_install.py
**Regression check**
- south, north, filter, notification plugins (delivery & rule), hybrid plugin 
- GET
- POST - when file_format=tar (Skip this test as we never used this)
- DELETE
- PUT
**O/P Results**
**Get - Plugins installed**
```
// http://localhost:8081/fledge/plugins/installed
{
"plugins": [
{
"name": "pi_server",
"type": "north",
"description": "PI Server North Plugin",
"version": "1.0.0",
"installedDirectory": "north/pi_server",
"packageName": "fledge-north-pi-server"
},
{
"name": "http_north",
"type": "north",
"description": "HTTP North Plugin",
"version": "1.8.1",
"installedDirectory": "north/http_north",
"packageName": "fledge-north-http-north"
},
{
"name": "ocs",
"type": "north",
"description": "OCS (OSIsoft Cloud Services) North Plugin",
"version": …
```
=> FOGL-4419 - API enhancements for notification plugin type info & installed directory, package info KV pair added to installed plugins

C/plugins/storage/sqlite/common/connection.cpp, C/plugins/storage/sqlite/common/include/connection.h, C/plugins/storage/sqlite/common/readings.cpp, C/plugins/storage/sqlitememory/connection.cpp, scripts/plugins/storage/sqlite/init_readings.sql
API used for the improvements:
**used by the GUI**
curl -s -S -X GET http://localhost:8081/fledge/asset | jq '.' 
**used by the GUI**
curl -s -S -X GET http://localhost:8081/fledge/asset/rand_1/summary?seconds=864000
**used by the GUI, it extract all the rows**
curl -s -S -X GET http://localhost:8081/fledge/asset/rand_1?seconds=864000 > /tmp/api3
**Fetch operation**
curl -s -S -X GET "http://localhost:${storage_port}/storage/reading?id=10000000&count=10" | jq "."
**Storage operation**
curl -s -S -X PUT http://localhost:${storage_port}/storage/reading/query -d @- <<EOF | jq "."
{
"where":{
"column":"asset_code",
"condition":"=",
"value":"rand_2",
"and":{
"column":"user_ts",
"condition":"older",
"value":600
}
},
"aggregate":[
{
"operation":"min",
"json":{
"column":"reading", …
=> Fogl 3596 : retrieval performance improvements for multi readings table

python/fledge/services/core/api/service.py, python/fledge/services/core/api/task.py, python/fledge/services/core/api/utils.py, tests/unit/python/fledge/services/core/api/test_api_utils.py
foglamp@foglamp-18:~/fledge$ curl -sX POST http://localhost:8081/fledge/scheduled/task -d \
'{
"name": "opcuabad",
"plugin": "opcuabad",
"type": "north",
"schedule_type": 3,
"schedule_day": 0,
"schedule_time": 0,
"schedule_repeat": 30,
"schedule_enabled": true
}'
{"message": "Plugin opcuabad does not appear to be a valid plugin"}
foglamp@foglamp-18:~/fledge$ curl -sX POST http://localhost:8081/fledge/service -d '{"name": "op", "plugin": "blah", "type": "south", "enabled": false}'
404: Plugin "blah" import problem from path "/home/aj/fledge/python/fledge/plugins/south/blah"
=> FOGL-4584 Improve error reporting for bad plugins

C/common/asset_tracking.cpp, C/plugins/north/OMF/omfhints.cpp, tests/unit/C/CMakeLists.txt, tests/unit/C/plugins/common/CMakeLists.txt
tested using the cases:
```
curl -sX POST http://localhost:8081/fledge/filter -d @- <<EOF
{
"name":"acce_h",
"plugin":"omfhint",
"filter_config":{
"hints":{
"fogbench_accelerometer": {
"datapoint":
{
"name": "x",
"integer": "int64"
}
}
}
}
}
EOF
curl -sX POST http://localhost:8081/fledge/filter -d @- <<EOF
{
"name":"acce_h",
"plugin":"omfhint",
"filter_config":{
"hints":{
"fogbench_accelerometer": {
"datapoint": [
{
"name": "x",
"integer": "int64"
},
{
"name": "y",
"integer":"int32"
}
]
}
}
}
}
EOF
curl -sX POST http://localhost:8081/fledge/filter -d @- <<EOF
{
"name": "acce_h",
"plugin": "omfhint",
"filter_config": {
"hints": {
"fogbench_luxometer": {
"number": "float32"
},
"fogbench_accelerometer": {
"number": "float32",
"datapoint": [
{ …
```
=> Fogl 4367 multidatapoints: adds array support to datapoint

VERSION, python/fledge/common/service_record.py, python/fledge/services/core/api/service.py, scripts/fledge, scripts/plugins/storage/postgres/downgrade/36.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/37.sql, scripts/plugins/storage/sqlite/downgrade/36.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/37.sql, scripts/services/north_C, tests/unit/python/fledge/services/core/api/test_service.py
**Curl Examples**
```
$ curl -X POST http://localhost:8081/fledge/service -d '{"name": "HT", "plugin": "http_north", "type": "north", "enabled": true}'
{"name": "HT", "id": "56b74fad-051c-49eb-b5d0-255fe348be20"}
$ curl -sX GET http://localhost:8081/fledge/category | jq
{
"categories": [....
{
"key": "HT",
"description": "HTTP North Plugin",
"displayName": "HT"
},
{
"key": "North",
"description": "North microservices",
"displayName": "North"
},
]
}
$ curl -sX GET http://localhost:8081/fledge/category/North | jq
{}
$ curl -sX GET http://localhost:8081/fledge/category/North/children | jq
{
"categories": [
{
"key": "HT",
"description": "HTTP North Plugin",
"displayName": "HT"
}
]
}
$ curl -sX GET http://localhost:8081/fledge/schedule/process …
```
=> FOGL-4690 north service type added for POST service API and related changes

scripts/plugins/storage/postgres/upgrade/36.sql, scripts/plugins/storage/postgres/upgrade/37.sql, scripts/plugins/storage/sqlite/upgrade/36.sql, scripts/plugins/storage/sqlite/upgrade/37.sql
**Sqlite**
```
upgrade
$ ./scripts/fledge start
Detected 'sqlite' Fledge DB schema change from version [35] to [37], applying Upgrade/Downgrade ...
Fledge DB schema has been upgraded to version [37]
Starting Fledge v1.8.2.......
Fledge started.
downgrade
$ ./scripts/fledge start
Detected 'sqlite' Fledge DB schema change from version [37] to [35], applying Upgrade/Downgrade ...
Fledge DB schema has been downgraded to version [35]
Starting Fledge v1.8.2.......
Fledge started.
```
**PostgreSql**
```
upgrade
$ ./scripts/fledge start
Detected 'postgres' Fledge DB schema change from version [35] to [37], applying Upgrade/Downgrade ...
Fledge DB schema has been upgraded to version [37]
Starting Fledge v1.8.2.......
Fledge started.
downgrade
$ …
```
=> FOGL-4717 upgrade scripts 36.sql & 37.sql unique constraint fixes and creates only if doesnot exist

python/fledge/services/core/api/scheduler.py, tests/unit/python/fledge/services/core/api/test_scheduler_api.py
Root cause was found by @praveen-garg 
On POST scheduled process entry scheduler gets stucked (corrupted scheduler process script dict)
Also We don't need to add south to see scheduler gets stopped, it gets corrupted as soon as service agent make an entry for FogMan Agent Poll task.
=> FOGL-4689 scheduler process_script corruption fixes which causes scheduler gets stopped

python/fledge/services/core/api/common.py, tests/system/python/api/test_common.py, tests/unit/python/fledge/services/core/api/test_common_ping.py
```
// http://192.168.1.9:8081/fledge/ping
{
"uptime": 59,
"dataRead": 29,
"dataSent": 0,
"dataPurged": 0,
"authenticationOptional": true,
"serviceName": "Fledge",
"hostName": "aj",
"ipAddresses": [
"192.168.1.9"
],
"health": "green",
"safeMode": false,
"version": "1.8.2"
}
```
**NOTE** -  ~Onwards with bump/next released version we need to update these tests as well (as per released version number) to make sure version info verification is fine with bumped version in /ping~
=> FOGL-3921 version info added to ping JSON response along with their unit/system tests

C/services/common/plugin_manager.cpp
FOGL-3212: set warning message instead of error for missing plugin directories
=> FOGL-3212: set warning message instead of error for missing plugin directories

C/services/south/include/ingest.h, C/services/south/ingest.cpp
Readings that fail to insert into the storage layer cause the south service to retry them forever. This increases the memory usage of the south service and eventually causes a failure to occur when memory is exhausted.
=> FOGL-4783 Prevent bad readings clogging up ingest queue

C/common/JSONPath.cpp, C/common/string_utils.cpp, tests/unit/C/common/test_JSONPath.cpp
Add support for non-string types inn JSONPath match, e.g. /device[id==1]/name,
and Improve error reporting.
=> FOGL-4883 Add support for non-string types in JSONPath matching

C/plugins/storage/sqlite/common/connection_manager.cpp, C/plugins/storage/sqlite/common/include/connection.h, C/plugins/storage/sqlite/common/readings.cpp, C/plugins/storage/sqlite/common/readings_catalogue.cpp, C/services/storage/configuration.cpp, C/services/storage/storage.cpp
checking C unit tests:
valgrind output:
```
==00:00:02:09.662 24458== LEAK SUMMARY:
==00:00:02:09.662 24458==    definitely lost: 0 bytes in 0 blocks
==00:00:02:09.662 24458==    indirectly lost: 0 bytes in 0 blocks
==00:00:02:09.662 24458==      possibly lost: 625,176 bytes in 147 blocks
==00:00:02:09.662 24458==    still reachable: 5,599,860 bytes in 2,279 blocks
==00:00:02:09.662 24458==                       of which reachable via heuristic:
==00:00:02:09.662 24458==                         length64           : 635,160 bytes in 2,012 blocks
==00:00:02:09.662 24458==         suppressed: 0 bytes in 0 blocks
```
=> FOGL-4882: memory leak fix

scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/sqlite/init.sql
Note: For sqlite init.sql added the schema details for the sake of consistency although it is not required.
=> FOGL-5053: Added the schema while creating the packages table

docs/rest_api_guide/02_RESTadmin.rst, python/fledge/services/core/api/audit.py, tests/system/python/api/test_audit.py, tests/unit/python/fledge/services/core/api/test_audit.py
FOGL-3125: fix for adding audit entries in Postgres
=> FOGL-3125, FOGL-5121: Update  audit entries tests

C/plugins/north/OMF/omf.cpp
Log samples
```
North_Readings_to_PI[22905]: DEBUG: setMapObjectTypes - The type of the datapoint tuesday/maxPosition is unsupported, it will be ignored
North_Readings_to_PI[22905]: DEBUG: setMapObjectTypes - The type of the datapoint tuesday/minPosition is unsupported, it will be ignored
```
=> FOGL-5439: avoid handling unsupported types

C/common/include/datapoint.h
and once from DatapointValue destructor
=> FOGL-5490 deleteNestedDPV called twice, once from Datapoint destructor

python/fledge/services/core/api/certificate_store.py, tests/unit/python/fledge/services/core/api/test_certificate_store.py
**Example**
1) Upload **.der** binary cert
```
$ curl -F "cert=@aj.der" http://localhost:8081/fledge/certificate
{"result": "aj.der has been uploaded successfully"}
```
2) Get certs - See **aj.der** entry is there
```
$ curl -sX GET http://localhost:8081/fledge/certificate | jq
{
"certs": [
"user.cert",
"ca.cert",
"fledge.cert",
"aj.der",
"admin.cert",
"fledge.pem"
],
"keys": [
"admin.key",
"ca.key",
"fledge.key",
"user.key"
]
}
```
3) DELETE **aj.der** cert
```
$ curl -sX DELETE http://localhost:8081/fledge/certificate/aj.der | jq
{
"result": "aj.der has been deleted successfully"
}
```
4) GET certs - There is no **aj.der** entry exists after deletion
```
$ curl -sX GET http://localhost:8081/fledge/certificate | jq
{
"certs": [ …
```
=> FOGL-5546 support added for binary .der format in cert store API

python/fledge/services/core/api/certificate_store.py, tests/unit/python/fledge/services/core/api/test_certificate_store.py
**Curl Examples**
1) $ curl -F "cert=@aj.p" http://localhost:8081/fledge/certificate
```
400: Accepted file extensions are ('.cert', '.cer', '.csr', '.crl', '.crt', '.der', '.json', '.pem', '.p12', '.pfx') for cert file
```
2) $ curl -sF "cert=@aj.crl" http://localhost:8081/fledge/certificate | jq
```
{
"result": "aj.crl has been uploaded successfully"
}
```
3) $ curl -sF "cert=@aj.csr" http://localhost:8081/fledge/certificate | jq
```
{
"result": "aj.csr has been uploaded successfully"
}
```
4) $ curl -sF "cert=@aj.p12" http://localhost:8081/fledge/certificate | jq
```
{
"result": "aj.p12 has been uploaded successfully"
}
```
5) $ curl -sF "cert=@aj.pfx" http://localhost:8081/fledge/certificate | jq
```
{
"result": "aj.pfx has been …
```
=> FOGL-5480 more short cert extensions support added in certificate store API

tests/system/python/conftest.py, tests/system/python/helpers/utils.py, tests/system/python/packages/test_omf_north_service.py
Tests with different scenarios related to north service are complete.
Pending Items related to filters with North service:
=> FOGL-5474: System test for OMF as north service

C/plugins/north/OMF/include/omf.h, C/plugins/north/OMF/omf.cpp, C/plugins/north/OMF/plugin.cpp, tests/unit/C/plugins/common/test_omf_translation.cpp, tests/unit/C/plugins/common/test_omf_translation_piwebapi.cpp
ContainerId = Asset Name
**Type changes**
2nd uses 
```
curl -s -S -X PUT http://localhost:8081/fledge/category/${north_instance}/NamingScheme -d '{ "value" : "Use Attribute Hash" }' | jq "."
```
```
North_Readings_to_PI[11275]: WARNING: xxx2 OMF plugin: current element '4273005507977094880_asset_1' doesn't have 'namingScheme' property, handling naming scheme in compatibility mode
North_Readings_to_PI[11275]: WARNING: xxx2 OMF plugin: current element '4273005507977094880_asset_2' doesn't have 'namingScheme' property, handling naming scheme in compatibility mode
```
=> FOGL-5573: Change default behavior of OMF North plugin to have concise naming

docs/scripts/fledge_plugin_list, docs/scripts/plugin_documentation
Note: `?per_page=1000` fetches only 100 repositories which is the maximum limit. For more details please refer to https://docs.github.com/en/rest/guides/traversing-with-pagination#changing-the-number-of-items-received
=> FOGL-5040: Removed hard-coded page count value in fetching GitHub repos

python/fledge/services/core/api/repos/configure.py
**Tested on AWS-ub20**
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ python3 -V
Python 3.8.10
$ python3
>>> import platform
>>> platform.platform()
'Linux-5.4.0-1038-aws-x86_64-with-glibc2.29'
```
**Curl Request**
```
$ curl -sX POST http://localhost:8081/fledge/repository -d '{"url":"http://archives.fledge-iot.org"}'
{"message": "Package repository configured successfully.", …
```
=> FOGL-5579 ub20 support added in POST repository endpoint

tests/system/python/scripts/package/remove
Changed the order of commands, because if fledge packages are not installed then the purge command fails and exits with a non-zero exit code. This non-zero exit code causes failure in packages-based system tests.
=> FOGL-5142: Changed the order of commands

docs/building_fledge/building_fledge.rst, docs/quick_start/installing.rst
1. If you need to install APT packages via sudo with noninteractive, use: sudo before
```
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y [PACKAGE_NAME]
```
2. quote fixes
```
$ sudo add-apt-repository ‘deb http://archives.fledge-iot.org/latest/ubuntu1804/x86_64/ / ‘
Error: need a single repository as argument
```
=> documentation fixes

python/fledge/services/core/support.py
See the version file added into support bundle
```
$ tar -xvf support-210910-13-33-26.tar.gz 
fledge-info
syslog-210910-13-33-26
syslogStorage-210910-13-33-26
syslog-si-210910-13-33-26
configuration-210910-13-33-26
audit-210910-13-33-26
schedules-210910-13-33-26
scheduled_processes-210910-13-33-26
statistics-history-210910-13-33-26
plugin-data-210910-13-33-26
streams-210910-13-33-26
service_registry-210910-13-33-26
machine-210910-13-33-26
psinfo-210910-13-33-26
package_logs/
software-210910-13-33-26
```
See the content for version
```
$ cat fledge-info 
[
"fledge_version=1.9.1",
"fledge_schema=43"
]
```
=> FOGL-5912 fledge version added & 'a' flag which is equivalent to binary file with grep commands to get  full syslogs in support bundle

C/services/common/include/binary_plugin_handle.h, C/services/common/include/plugin_manager.h, C/services/common/plugin_manager.cpp, C/services/storage/storage.cpp
log samples 
```
Storage[1488]: DEBUG: BinaryPluginHandle - storage plugin / RTLD_LAZY - name :sqlite: path :/home/foglamp/Development/fledge/plugins/storage/sqlite/libsqlite.so:
Storage[1488]: DEBUG: BinaryPluginHandle - storage plugin / RTLD_LAZY - name :sqlitememory: path :/home/foglamp/Development/fledge/plugins/storage/sqlitememory/libsqlitememory.so:
North_Readings_to_PI[1672]: DEBUG: BinaryPluginHandle - other plugin / RTLD_LAZY|RTLD_GLOBAL - name :OMF: path :/home/foglamp/Development/fledge/plugins/north/OMF/libOMF.so:
```
=>   FOGL-5977  With sql-in-memory database configuration, readings are ingested in sqlite db

scripts/plugins/storage/postgres.sh, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/sqlite.sh, scripts/plugins/storage/sqlitelb.sh
PostgreSQL forcing error 
```
foglamp@ihsdev:~$ echo -e "YES" | ${FLEDGE_SCRIPT} reset
This script will remove all data stored in the server.
Enter YES if you want to continue: [2021-11-09 10:28:52]: Storage script.plugin.storage.postgres err psql:/home/foglamp/Development/fledge/scripts/plugins/storage/postgres/init.sql:51: ERROR:  database "fledge" is being accessed by other users
DETAIL:  There is 1 other session using the database.
psql:/home/foglamp/Development/fledge/scripts/plugins/storage/postgres/init.sql:56: ERROR:  database "fledge" already exists
psql:/home/foglamp/Development/fledge/scripts/plugins/storage/postgres/init.sql:69: ERROR:  schema "fledge" already exists
psql:/home/foglamp/Development/fledge/scripts/plugins/storage/post …
```
=> FOGL-6054  Fledge reset : Fledge reset does not report if there are errors in the execution of the init.sql

python/fledge/services/core/api/notification.py, python/fledge/services/core/routes.py, tests/unit/python/fledge/services/core/api/test_notification.py
Below are the curl API results
Let say **overspeed** is a notification instance name
```
$ curl -sX GET http://localhost:8081/fledge/notification/overspeed/delivery | jq
{
"channels": []
}
```
```
$ curl -sX POST http://localhost:8081/fledge/notification/overspeed/delivery -d '{"name": "coolant", "config": {"action": {"description": "Perform a control action to turn pump", "type": "boolean", "default": "false"}}}' | jq
{
"category": "overspeed_channel_coolant",
"description": "coolant delivery channel",
"config": {
"action": {
"description": "Perform a control action to turn pump",
"type": "boolean",
"default": "false"
}
}
}
$ curl -sX GET http://localhost:8081/fledge/notification/overspeed/delivery | jq
{
"channels": [
"coolant"
]
}
```
```
$ curl -sX GET …
```
=> FOGL-6077 - New API addition for multiple delivery channels

python/fledge/services/core/api/browser.py, tests/unit/python/fledge/services/core/api/test_browser_assets.py
**Sample Output1**
```
With system info plugin
$ curl -sX GET http://localhost:8081/fledge/asset/system%2FcpuUsage_all/latest | jq
[
{
"reading": {
"prcntg_usr": 12.66,
"prcntg_nice": 0.06,
"prcntg_sys": 2.45,
"prcntg_iowait": 1.43,
"prcntg_irq": 0,
"prcntg_soft": 0.56,
"prcntg_steal": 0,
"prcntg_guest": 0,
"prcntg_gnice": 0,
"prcntg_idle": 82.85
},
"timestamp": "2021-12-13 13:12:49.479095"
}
]
Equivalent to below request
$ curl -sX GET http://localhost:8081/fledge/asset/system%2FcpuUsage_all?limit=1 | jq
[
{
"reading": {
"prcntg_usr": 12.66,
"prcntg_nice": 0.06,
"prcntg_sys": 2.45,
"prcntg_iowait": 1.43,
"prcntg_irq": 0,
"prcntg_soft": 0.56,
"prcntg_steal": 0,
"prcntg_guest": 0,
"prcntg_gnice": 0,
"prcntg_idle": 82.85
},
"timestamp": …
```
=> FOGL-6116 New endpoint added in API to get latest reading for an asset

python/fledge/services/core/api/control_service/acl_management.py, python/fledge/services/core/routes.py
**Curl Sample Output**
```
$ curl -H "authorization: $AUTH_TOKEN" -sX PUT http://localhost:8081/fledge/service/Sine/ACL -d '{"acl_name": "testACL"}' | jq
{
"message": "testACL ACL attached to Sine service successfully"
}
$ curl -H "authorization: $AUTH_TOKEN" -sX GET http://localhost:8081/fledge/category/SineSecurity | jq
{
"AuthenticatedCaller": {
"description": "Caller authorisation is needed",
"type": "boolean",
"default": "false",
"displayName": "Enable caller authorisation",
"value": "false"
},
"ACL": {
"description": "Service ACL for Sine",
"type": "JSON",
"displayName": "Service ACL",
"default": "{\"service\": {\"name\": \"IEC-104\", \"type\": \"notification\"}, \"url\": {\"URL\": \"/fledge/south/operation\"}}",
"value": "{\"service\": {\"name\": \"IEC-104\", \"type\": …
```
=> Fogl 6065 - Attach ACL to service and Detach ACL from service endpoints added

python/fledge/services/core/api/browser.py, tests/unit/python/fledge/services/core/api/test_browser_assets.py
Curl sample Output for large string will be replaced with placeholder string for browser endpoints. I have used testcard plugin which is only available in FOGL-5665 branch
```
$ curl -sX GET localhost:8081/fledge/asset/testcard  | jq
[
{
"reading": {
"testcard": "Data removed for brevity"
},
"timestamp": "2022-02-14 19:36:37.430813"
}
]
$ curl -sX GET localhost:8081/fledge/asset/testcard/summary  | jq
[
{
"testcard": {
"min": "Data removed for brevity",
"max": "Data removed for brevity",
"average": 0
}
}
]
$ curl -sX GET localhost:8081/fledge/asset/testcard/testcard  | jq
[
{
"timestamp": "2022-02-14 19:38:25.246580",
"testcard": "Data removed for brevity"
},
{
"timestamp": "2022-02-14 19:38:24.246530",
"testcard": "Data removed for brevity"
},
$ curl -sX GET …
```
=> FOGL-6173 - Filtering of images data in browser endpoint (Part-A)

C/common/result_set.cpp
Handle generic array as JSON value
"steps" is an array of generic objects
```
{
"steps": [
{
"write": {
"order": 0,
"service": "SIN1",
"values": {
"D": "69"
}
}
},
{
"a": 5
}
]
}
```
=> FOGL-6240: Handle generic array as JSON value

docs/control.rst
Also we should avoid Product prefix usage in titles, subtitles etc.
=> title overline short fixes for whitelabelling & other typo fixes

tests/system/lab/install, tests/system/lab/test, tests/system/python/packages/data/package_list.json, tests/system/python/packages/test_lab.py, tests/system/python/rpi/test_e2e_rpi_ephat.py
As we renamed the envirohpat plugin with rpienviro. Therefore replaced the occurrences in tests directory.
http://archives.fledge-iot.org/nightly/buster/armv7l/fledge-south-rpienviro_1.9.2-8_armv7l.deb
=> FOGL-6239 use rpienviro plugin name in tests instead envirophat

C/services/south/south.cpp
FOGL-6322: call southPlugin->start() only for async plugins
=> FOGL-6322: call southPlugin->start() only for async plugins

docs/control.rst
https://fledge-iot.readthedocs.io/en/develop/control.html#configuration - In develop title is missing
With the given change you will be see the proper title under Configuration header.
=> Title level inconsistency fixes in control documentation

C/common/pythonreading.cpp
I added a small change to give better information about the “numpy.core.multiarray failed to import“ error. So it is not really a fix per se but it did help the situation and issue is not seen by me and Yash anymore. 
Also we added “python3-numpy” to list of run-time dependencies in fledge-pkg’s CONTROL file. This is in a separate PR that Yash would send out for review.
=> FOGL-6337: Adding some debug logs around import_array call

C/services/filter-plugin-interfaces/python/filter_ingest_pymodule/ingest_callback_pymodule.cpp
Checked with valgrind also - no memory leak related to readings.
This also fixes the crash seen with 3 instances of csv-writer in a single south service instance.
=> FOGL-6407: can't free borrowed references; 

docs/requirements.txt, python/requirements-doc.txt, python/requirements-test.txt
Fixed CVE Alerts for following
=> FOGL-6399  Some python pip packages updated which causing CVE alerts

scripts/fledge
```
$ ./scripts/fledge status
Fledge v1.9.2 running.
Fledge Uptime:  82941 seconds.
Fledge records: 1273 read, 875 sent, 0 purged.
fledge.services.storage --address=0.0.0.0 --port=46455
fledge.services.south --port=46455 --address=127.0.0.1 --name=s 
fledge.services.north --port=46455 --address=127.0.0.1 --name=HTPS 
fledge.services.notification --port=46455 --address=127.0.0.1 --name=AJ Notify 
fledge.services.dispatcher --port=46455 --address=127.0.0.1 --name=DispatcherServer 
=== Fledge tasks:
fledge.tasks.north.sending_process --port=46455 --address=127.0.0.1 --name=HTPP
```
=> FOGL-6412 token is omitted from status output

python/fledge/services/core/api/support.py, tests/unit/python/fledge/services/core/api/test_support.py
**RpiZero With buster**
Time below are in seconds:
A) _With develop branch_
```
$ curl -sX GET "http://localhost:8081/fledge/syslog" | jq '.count'
1905
pi@raspberrypi:~ $ for ((i=1;i<=5;i++)); do curl -w "@curl-format.txt" -o /dev/null -sX GET "http://localhost:8081/fledge/syslog"; done
time_namelookup:  0.017341s
time_connect:  0.019816s
time_appconnect:  0.000000s
time_pretransfer:  0.020298s
time_redirect:  0.000000s
time_starttransfer:  0.289641s
----------
time_total:  0.290942s
time_namelookup:  0.020024s
time_connect:  0.024859s
time_appconnect:  0.000000s
time_pretransfer:  0.025395s
time_redirect:  0.000000s
time_starttransfer:  0.366492s
----------
time_total:  0.372889s
time_namelookup:  0.020675s
time_connect:  0.023197s
time_appconnect:  0.000000s
time_pretransfer:  0.023670s …
```
=> FOGL-6461 Update syslog entries commands

C/services/common-plugin-interfaces/python/include/python_plugin_common_interface.h, C/services/south-plugin-interfaces/python/python_plugin_interface.cpp, docs/plugin_developers_guide/03_02_south_python_Control.rst, docs/plugin_developers_guide/03_south_plugins.rst
Also added support for plugin mode to have multiple flags set (separated by pipe symbol '|') e.g. "poll|control" in python plugins.
=> FOGL-5195: Add support for control in Python south plugins

tests/system/python/api/test_audit.py, tests/system/python/api/test_configuration.py
**Note** - I also ran custom Job to check health system test with given change and now system tests passes on both Sqlite and PostgreSQL engines.
=> Fogl 6521.patch Configuration and Audit system tests updated

C/plugins/storage/postgres/connection.cpp
FOGL-6467: allow a single double quote escape in Postgres PUT endpoint
=> FOGL-6467: allow a single double quote escape in Postgres PUT endpoint

C/plugins/utils/get_plugin_info.cpp, tests/unit/C/common/test_python_reading.cpp, tests/unit/C/common/test_python_reading_set.cpp, tests/unit/C/common/test_python_readingnumpy.cpp, tests/unit/C/scripts/RunAllTests.sh
Reported segfault was probably because system ran out of RAM when run with default "-j4" option for make command, which was too much for a RPi with 1 GB RAM.
=> FOGL-6945: Acquire and release GIL properly around calls to embedded Python library

C/services/south/ingest.cpp
=> Syslogs are overflooded "ERROR: Failure to get StorageAssetTracking record for service" when Asset tracker entry write to storage

python/fledge/services/core/scheduler/scheduler.py
note: Add schedule makes two entries SCHAD and SCHCH (as expected in code). 
Now, We should see only one entry for change in schedule, be it enabled or other attributes/properties; individual or along with others .
=> FOGL-7005 Fix enable/disable a schedule causing double audit entries for Schedule Change event

tests/system/python/e2e/test_e2e_coap_PI.py, tests/system/python/e2e/test_e2e_csv_PI.py, tests/system/python/e2e/test_e2e_csv_multi_filter_pi.py, tests/system/python/e2e/test_e2e_expr_pi.py, tests/system/python/e2e/test_e2e_filter_fft_threshold.py, tests/system/python/e2e/test_e2e_modbus_c_pi.py, tests/system/python/e2e/test_e2e_pi_scaleset.py, tests/system/python/e2e/test_e2e_vary_asset_http_pi.py, tests/system/python/pair/test_e2e_fledge_pair.py
For connector relay we should not delete PI Point because 
when the PI point is created again (after deletion) the compressing attribute for it 
is always true. That means all the data is not stored in PI data archive. 
We lose a large proportion of the data because of compressing attribute.
This is problematic for the fixture that verifies the data stored in PI.
=> Commented out fixtures for cleaning PI system specially for connector relay system tests.

VERSION, python/fledge/common/web/middleware.py, scripts/plugins/storage/postgres/downgrade/58.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/59.sql, scripts/plugins/storage/sqlite/downgrade/58.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/59.sql, scripts/plugins/storage/sqlitelb/downgrade/58.sql, scripts/plugins/storage/sqlitelb/init.sql, scripts/plugins/storage/sqlitelb/upgrade/59.sql, tests/system/python/api/test_authentication.py, tests/system/python/api/test_endpoints_with_different_user_types.py
=> FOGL-7060 New user role types & some restrictions added to API as per user

C/plugins/storage/postgres/connection.cpp
With this setting, all timezone-aware timestamps are returned in 'UTC' rather than configured time zone.
=> FOGL-7179: Set session level time zone for Postgres DB connection to 'UTC'

C/services/storage/storage.cpp, scripts/common/get_readings_plugin.sh, scripts/services/storage, scripts/storage
storage plugin.
No one issue that could be improved is that two warnings are issued when doing a reset operations, one for each plugin.
=> FOGL-7227 Run purge operations on readings plugins if different from the

python/fledge/common/utils.py, python/fledge/common/web/ssl_wrapper.py, tests/system/python/api/test_plugin_discovery.py, tests/system/python/api/test_service.py, tests/system/python/scripts/install_c_plugin
`fledge_nightly_build_centos_stream_9/27/` - Now those tests are passing
Note: Tests file will be reverted in FOGL-7260 branch & other TODO comments for x509 strict check
=> FOGL-7222 - Authentication system API tests & other non -notification tests fixes on CentOS9 stream

C/plugins/north/OMF/include/omf.h, C/plugins/north/OMF/omf.cpp, C/plugins/north/OMF/plugin.cpp
Can now send data to connector relay. Firced legacy =true for omf versions 1.1 and 1.0
=> FOGL-7298 OMF Connector relay fix - 2.1.0rc

python/fledge/services/core/api/python_packages.py, python/fledge/services/core/support.py
See the below output for downloaded support bundle
```
$ tar -tvf support-230116-12-49-59.tar.gz 
-rw-rw-r-- aj/aj            54 2023-01-16 12:49 fledge-info
-rw-rw-r-- aj/aj         64436 2023-01-16 12:49 syslog-230116-12-49-59
-rw-rw-r-- aj/aj         10264 2023-01-16 12:49 syslogStorage-230116-12-49-59
-rw-rw-r-- aj/aj         20675 2023-01-16 12:49 configuration-230116-12-49-59
-rw-rw-r-- aj/aj         24051 2023-01-16 12:49 audit-230116-12-49-59
-rw-rw-r-- aj/aj          2621 2023-01-16 12:49 schedules-230116-12-49-59
-rw-rw-r-- aj/aj          1978 2023-01-16 12:49 scheduled_processes-230116-12-49-59
-rw-rw-r-- aj/aj         10551 2023-01-16 12:49 statistics-history-230116-12-49-59
-rw-rw-r-- aj/aj            34 2023-01-16 12:49 plugin-data-230116-12-49-59
-rw-rw-r-- aj/aj …
```
=> FOGL-7311 python pip packages info added in support bundle

docs/OMF.rst
Update documentation of the AF Location hint to remove references to OMF Container terminology and describe instead the creation of AF Elements and Attributes in the AF Database. Added outline of the differences in behavior between the original Complex Types and the new Linked Types configuration.
Signed-off-by: Ray Verhoeff <ray@dianomic.com>
=> FOGL-6765: Update AF Location Hint documentation

C/common/audit_logger.cpp, C/common/include/audit_logger.h, C/common/include/process.h, C/common/process.cpp, C/plugins/north/OMF/include/omf.h, C/plugins/north/OMF/omf.cpp, C/plugins/north/OMF/plugin.cpp, C/services/north/include/north_service.h, C/services/north/north.cpp, C/services/south/include/south_service.h, C/services/south/south.cpp, tests/unit/C/plugins/common/test_omf_translation.cpp
example in OMF north plugin
Improvements to OMF are required to be able to report all variants of the audit log, this is merely an example of the mechanism, currently.
=> FOGL-7421 Add mechanism for C++ plugins to add audit data and implement

C/plugins/north/OMF/linkdata.cpp, C/plugins/north/OMF/omf.cpp, C/plugins/north/OMF/plugin.cpp
Moved setting of OMF Version to _plugin_start_; this does not need to be repeated in _plugin_send_. Cleaned up error messages. Recategorized many _Info_ messages as _Debug_. Changed _action_ code for Linked Type Data messages from _create_ to _update_ which avoids creating duplicate PI data values if sending of data is repeated. I did not edit any of the REST error messages labelled "FIXME;" I think they are reasonable as-is.
=> FOGL-7428A: Clean up error logs

C/services/common/management_api.cpp
Errors in JSON configuration files have been causing crashes in the north service. This can occur if the JSON is malformed but also if any subsequent processing fails. This has been addressed by adding an exception handler to the configuration change method.
=> FOGL-7507: add exception handler to configuration change

python/fledge/services/core/api/plugins/remove.py, python/fledge/services/core/api/plugins/update.py, python/fledge/services/core/routes.py, tests/unit/python/fledge/services/core/api/plugins/test_remove.py, tests/unit/python/fledge/services/core/api/plugins/test_update.py
~Note: I haven't changed the param in request - name Vs PackageName. So we need to decide for the backward compatability by checking fledge core version `check > 2.1.0`; as this endpoint is only use by FogLAMP Manage.~
~As this endpoint is to update the package. So we should request with package name to make more clarity in the endpoint.~
New endpoints available with 2.1.0 onwards core version. More, details added on JIRA
```
PUT /fledge/plugins/{package_name}
DELETE /fledge/plugins/{package_name}
```
=> FOGL-7579 package name handling in Plugins PUT & DELETE API

C/plugins/storage/sqlite/common/include/readings_catalogue.h, C/plugins/storage/sqlite/common/readings_catalogue.cpp, tests/system/python/packages/test_multiple_assets.py
A separate non-blocking thread is used to schedule to check for empty table to remove delay in asset creation.
Purge schedule and purge option from developer tab also uses same class method which is being in thread. So working fine with manual purge from developer tab and purge schedule.
=> FOGL-7567: Modified to remove delay in asset creation

C/plugins/north/OMF/include/basetypes.h
There were a few trailing commas in the integer type definitions in the baseOMFTypes JSON string. The PI Web API overlooked this but AVEVA Data Hub (ADH) could not process the JSON and logged an error instead. This affected subsequent Stream creation. This has been fixed.
=> FOGL-7589: Fixed typos in OMF base types JSON

python/fledge/common/configuration_manager.py, tests/unit/python/fledge/common/test_configuration_manager.py
Below is one of example to show audit **CONCH** record entry when having different configuration
```
{
"audit": [{
"details": {
"category": "sine", 
"item": "configurationChange",
"oldValue": {"plugin": {"description": "Sinusoid Poll Plugin which implements sine wave with data points", "type": "string", "default": "sinusoid", "readonly": "true", "value": "sinusoid"}, "assetName": {"description": "Name of Asset", "type": "string", "default": "sinusoid", "displayName": "Asset name", "mandatory": "true", "value": "sinusoid"}}, 
"newValue": {"plugin": {"description": "Sinusoid Poll Plugin which implements sine wave with data points", "type": "string", "readonly": "true", "default": "sinusoid", "value": "sinusoid"}, "assetName": {"description": "Name of Asset", "type": "string", "displayName": …
```
=> FOGL-7599 CONCH audit log record added when configuration change happens

python/fledge/services/core/api/task.py, python/fledge/services/core/api/utils.py
=> some log fixes in python API

python/fledge/common/logger.py
Note - We need to revisit logger error/exception messages to get traceback in multiline via another JIRA. First, we will track down Python core and then Admin API.
=> FOGL-7432 override logging error in python logger class

C/plugins/north/OMF/plugin.cpp
This work item has been completed and closed before ([FOGL-7526](https://scaledb.atlassian.net/browse/[FOGL-7526](https://scaledb.atlassian.net/browse/FOGL-7526))). However, during testing of AVEVA's latest release of the Edge Data Store (EDS 2023 Patch 1) with the OMF North plugin, it was discovered that the REST endpoint that returns the product version has been changed. The product version string is in a different position in the JSON response document which caused the parsing code to miss it. This Pull Request fixes the version string parsing so it will properly detect both EDS 2020 and EDS 2023 versions.
=> FOGL-7526A: Adjust product version check for changes in EDS 2023

python/fledge/common/logger.py
This primarily has the fix of below cases:
a) string format when having with %s as it prints as is
```
For example:
_logger.error('Failed to log audit trail entry for code: %s', "CONCH")
O/P
Failed to log audit trail entry for code: %s
```
b) non-Exception cases 
For example:
```
color_list = ['Orange', 'White', 'Green']
i) _logger.error(color_list)
color_dict = {'colors': {'Orange', 'White', 'Green'}}
ii) _logger.error(color_dict)
iii) _logger.error(type(request))
O/p
i) 'list' object has no attribute 'splitlines'
ii) 'dict' object has no attribute 'splitlines'
iii) type object 'Request' has no attribute 'splitlines'
```
This needs to get merged ASAP to block others
=> FOGL-7685 args fixes in logger and other fixes

docs/requirements.txt
=> Readthedocs build failure fixes as latest urllib3 version is not compatible

C/common/pythonreading.cpp
For north Python plugins, when converting T_DP_DICT/T_DP_LIST readings to PyObject, new DICT/LIST is being created for each datapoint.
=> FOGL-7861: Memory growth on north service for DICT and LIST readings.

C/services/north/data_send.cpp
Regression caused by FOGL-7862.
=> FOGL-7898: Readings being skipped when not sent by north plugin

C/plugins/storage/sqlite/common/readings.cpp
On calling below
```
curl -sX PUT localhost:34259/storage/reading/query -d '{"sort": {"column": "asset_code", "direction": "asc"}}'
```
Though it returns 200 http status code. But there is a syntax error on Sql query
Error:
```
Jul 20 19:09:05 AJ Fledge Storage[32692]: ERROR: SQLite3 storage plugin raising error: near ")": syntax error
```
=> Sql query syntax fixes

scripts/plugins/storage/postgres/downgrade/61.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/62.sql, scripts/plugins/storage/sqlite/downgrade/61.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/62.sql, scripts/plugins/storage/sqlitelb/downgrade/61.sql, scripts/plugins/storage/sqlitelb/init.sql, scripts/plugins/storage/sqlitelb/upgrade/62.sql
Fixed items
NOTE: We should not use `timestamp` (reserved) name column . As in fledge schema we usually with `ts` column.
=> FOGL-7994.patch

C/plugins/storage/sqlitelb/common/readings.cpp, python/fledge/common/storage_client/storage_client.py, tests/unit/python/fledge/common/storage_client/test_storage_client.py
OLD
```
$ curl -sX PUT "http://localhost:42703/storage/reading/purge?age=72&sent=0&flags=purge"
{ "removed" : 0,  "unsentPurged" : 0,  "unsentRetained" : 0,  "readings" : 0 } "method" : "time",  "duration" : 0 }
```
With the given change
```
$ curl -sX PUT "http://localhost:42703/storage/reading/purge?age=72&sent=0&flags=purge" | jq
{
"removed": 0,
"unsentPurged": 0,
"unsentRetained": 0,
"readings": 0,
"method": "time",
"duration": 0
}
```
=> FOGL-8113 PURGE JSON response fixes when nothing to removed & more exception handling added in Python purge along with unit tests

C/services/south/south.cpp, docs/tuning_fledge.rst
service as the default for south services
This will be reverted after the next release and a GUI change done for the display of south services
=> FOGL-8190 Temporarily revert to statistics collection per asset and

tests/system/python/api/test_endpoints_with_different_user_types.py
Custom tests ran over - `fledge_postgresub1804/642` and now these tests are passing with PostgreSQL engine.
=> FOGL-7097 skip annotation removed from API tests as per FOGL-7960

C/plugins/north/OMF/omfinfo.cpp
The constructor of the new OMFInformation class read the AVEVA Data Hub (ADH) credentials from the plugin configuration but did not properly assign them to the OMFInformation member variables leaving them empty. All OMF calls would fail. The first REST call to fail was the authentication call which sent an empty Client Id and and empty Client Secret to ADH. This has been fixed.
=> FOGL-8220: Assign ADH credentials to OMFInformation member variables

python/fledge/common/configuration_manager.py, tests/unit/python/fledge/common/test_configuration_manager.py
[bucket_payload.json](https://github.com/fledge-iot/fledge/files/13437341/bucket_payload.json)
**Curl Examples**
- Create
```
$ curl -sX POST http://localhost:8081/fledge/category -d @bucket_payload.json 
{"key": "bucket", "description": "description", "value": {"model": {"description": "The machine learning model to use inspect the captured image for defects", "displayName": "QA Model", "order": "2", "type": "bucket", "properties": "{\"constant\": {\"type\": \"MLModel\",\"name\": \"BadBottle\"}, \"key\": {\"product\": {\"description\": \"The bottle type being produced\", \"displayName\": \"Bottle Type\",\"type\": \"enumeration\",\"options\": [\"Wine Bottle\",\"Bear Bottle\",\"Whiskey Bottle\",\"Milk Bottle\"],\"default\": \"Milk Bottle\"}},\"properties\": {\"version\": {\"description\": …
```
=> FOGL-8236 bucket type and properties optional attribute support added in configuration manager

C/common/include/service_record.h, python/fledge/common/configuration_manager.py, tests/unit/python/fledge/common/test_configuration_manager.py
**Tested With below samples**
[bucket_payload.json](https://github.com/fledge-iot/fledge/files/13741532/bucket_payload.json)
[FOGL-8349.json](https://github.com/fledge-iot/fledge/files/13741577/FOGL-8349.json)
Run the below script for POST, PUT, GET operations with above examples
[FOGL-8354.zip](https://github.com/fledge-iot/fledge/files/13741628/FOGL-8354.zip)
`sh FOGL-8354.sh`
**GET Response**
```
With Sample1:
{
"model": {
"description": "The machine learning model to use inspect the captured image for defects",
"displayName": "QA Model",
"order": "2",
"type": "bucket",
"properties": {
"constant": {
"type": "MLModel",
"name": "BadBottle"
},
"key": {
"product": {
"description": "The bottle type being produced",
"displayName": "Bottle Type",
"type": "enumeration",
"options": [
"Wine …
```
=> FOGL-8354 bucket properties converted to JSON object rather a string type in configuration manager

docs/OMF.rst
There is an error in the OMF North documentation that lists the OMF versions that align with AVEVA product versions ([FOGL-7649](https://scaledb.atlassian.net/browse/FOGL-7649))([Pull Request 1256](https://github.com/fledge-iot/fledge/pull/1256)). The error is in the OMF version applied to PI Web API 2019 (and all SPs): documentation said OMF 1.1; correct version is OMF 1.0.
We could also address this by changing the OMF North code so that we apply OMF 1.1 to the PI Web API 2019 releases. This would be a problem because we would have to retest OMF North with PI Web API 2019 if we do that.
This means that we never use OMF 1.1 to communicate with anything. I left the OMF 1.1 line in the table but it aligns with no AVEVA product versions. I could remove the line.
=> FOGL-7649A: Fix documentation of OMF version for PI Web API 2019

C/common/filter_pipeline.cpp
Made this change to enable python filters to connect to bucket service and get model files.
=> FOGL-8414: Pass management client URL/port in filter config

C/plugins/north/OMF/include/omf.h, C/plugins/north/OMF/omf.cpp, C/plugins/north/OMF/omfinfo.cpp, docs/OMF.rst
If the OMF North plugin gets an exception when POSTing data to the PI Web API, the plugin would declare the connection to PI broken when it wasn't. This would result in endless connection loss and reconnection messages. This has been fixed. The plugin will now ping the PI Web API every 60 seconds and will determine that connection has been lost if this ping fails.
The _OMFHint LegacyType_ has been deprecated. After a Container has been created in the PI System, it is not possible to change it. This means there is no way to process the _LegacyType_ hint when readings are processed. The only time it is possible to configure the plugin for legacy types is when a plugin instance is created. This is done by checking the _Complex Types_ box in the Fledge GUI. The LegacyType entry in the OMF …
=> FOGL-8388: Fix endless connection loss log messages and deprecate OMFHint LegacyType

python/fledge/services/core/api/control_service/pipeline.py, tests/system/python/api/test_service.py
Previously we calculate the difference of filters between lists with an unordered way. 
In the given fix, list order preserved for filters on CRUD's.
Also fixed one of the service based API tests which _sometimes_ fails on RPi boards. Therefore increased the wait time to avoid red flag in the test report.
=> FOGL-8462 Control Pipeline filter order fixes 

python/fledge/services/core/server.py, tests/system/python/api/test_alerts.py
```
$ pytest -s -vv tests/system/python/api/test_alerts.py 
tests/system/python/TestAlerts test_get_default_alerts <- api/test_alerts.py PASSED
tests/system/python/TestAlerts test_no_delete_alert <- api/test_alerts.py PASSED
tests/system/python/TestAlerts test_bad_delete_alert_by_key <- api/test_alerts.py PASSED
tests/system/python/TestAlerts test_create_alert <- api/test_alerts.py PASSED
tests/system/python/TestAlerts test_create_alert <- api/test_alerts.py PASSED
tests/system/python/TestAlerts test_get_all_alerts <- api/test_alerts.py PASSED
tests/system/python/TestAlerts test_delete_alert_by_key <- api/test_alerts.py PASSED
tests/system/python/TestAlerts test_delete_alert <- api/test_alerts.py PASSED
========================================================= 8 passed in 36.84 seconds …
```
=> FOGL-8451 User alerts API test added

tests/system/python/api/test_endpoints_with_different_user_types.py
| User Type  | HTTP VERB | API ENDPOINT | Action
| ------------- | ------------- |------------- |-------------------------|
| Admin  | GET  | <ul><li>/fledge/alert</li><li>/fledge/monitors</li></ul>       |  <ul><li>[x]  Allowed </li> |
| Admin  | DELETE  | <ul><li>/fledge/alert</li><li>/fledge/monitors</li></ul>       | <ul><li>[x]  Allowed </li> |
| Normal  | GET  | <ul><li>/fledge/alert</li><li>/fledge/monitors</li></ul>       |  <ul><li>[x]  Allowed </li> |
| Normal  | DELETE  | <ul><li>/fledge/alert</li><li>/fledge/monitors</li></ul>       | <ul><li>[x]  Allowed </li> |
| Control  | GET  | <ul><li>/fledge/alert</li><li>/fledge/monitors</li></ul>       |  <ul><li>[x]  Allowed </li> |
| Control  | DELETE  | <ul><li>/fledge/alert</li><li>/fledge/monitors</li></ul>       | <ul><li>[x] …
=> FOGL-8459 Performance monitors and user alerts endpoint verification in API tests with different users

docs/OMF.rst
The original bug report ([FOGL-8389](https://scaledb.atlassian.net/browse/FOGL-8389)) noted that disabling an _integer_ OMFHint generated errors and caused data to stop flowing to the PI Server. It turns out that OMF causes the PI Server to create AF Attributes and PI Points based on the original data type information. OMF cannot change these data types after the PI entities are created. The only change in this Pull Request is documentation to this effect. A procedure for detecting the problem and repairing the PI Server is included.
=> FOGL-8389: Problem changing data type formats

python/fledge/services/core/api/common.py
```
:~/fledge$ ./scripts/fledge kill; ./scripts/fledge start --safe-mode
Fledge killed.
Starting Fledge v2.3.0 in safe mode........
Fledge started.
~/fledge$ ./scripts/fledge status
Fledge v2.3.0 running in safe mode.
Fledge Uptime:  13 seconds.
Fledge records: 0 read, 0 sent, 0 purged.
fledge.services.storage --address=0.0.0.0 --port=46103
=== Fledge tasks:
~/fledge$ curl -sX GET localhost:8081/fledge/ping
{"uptime": 20, "dataRead": 0, "dataSent": 0, "dataPurged": 0, "authenticationOptional": true, "serviceName": "Fledge", "hostName": "ip-10-0-0-163", "ipAddresses": ["10.0.0.163"], "health": "green", "safeMode": true, "version": "2.3.0", "alerts": 0}
```
=> alert count fixes in both normal and safe mode; as used in Ping response

C/common/json_utils.cpp, tests/unit/C/common/test_json_utils.cpp
When escaping a large json string, we get a performance issue. 
I tested with a 30000 assets data exchange json and unescaping last around 20s while with new code only 20ms (1000 times faster).
=> Fix JSON unescaping performance issue

C/services/north/CMakeLists.txt, C/services/north/north.cpp, C/services/south/CMakeLists.txt, C/services/south/south.cpp, C/services/storage/CMakeLists.txt, C/services/storage/storage.cpp
- Added Profiling option to CMake for south/north/storage services.
* Use option  -DCMAKE_BUILD_TYPE=Profiling in Makefile to enable profiling build. Profiling information for each service will be created in seperate folders namely 'Southbound_Profile', 'Northbound_Profile' and 'Storage_Profile', each of these folders will be located in FLEDGE_ROOT/services.
=> FOGL-8608: New 'Profiling' build type to CMake.

C/plugins/storage/sqlite/common/connection.cpp, C/plugins/storage/sqlite/common/readings.cpp, C/plugins/storage/sqlite/common/readings_catalogue.cpp
Crash was due to double free for a sqlite's error msg buffer. That is fixed. But DB file is corrupted:
```
Jul 10 12:45:06 193PRC-EGD0001 FogLAMP Storage[834311]: ERROR: SQL statement DELETE FROM foglamp.statistics_history WHERE history_ts <= '2024-06-10 12:45:04.778127'; failed after maximum retries
Jul 10 12:45:06 193PRC-EGD0001 FogLAMP Storage[834311]: ERROR: Database error after maximum retries, executing DELETE operation on statistics_history
Jul 10 12:45:06 193PRC-EGD0001 FogLAMP Storage[834311]: ERROR: SQLite3 storage plugin raising error: delete: database disk image is malformed
Jul 10 12:45:06 193PRC-EGD0001 FogLAMP Storage[834311]: ERROR: SQL statement: DELETE FROM foglamp.statistics_history WHERE history_ts <= '2024-06-10 12:45:04.778127';
Jul 10 12:45:06 193PRC-EGD0001 FogLAMP …
```
=> FOGL-8899: Fix for double free

python/requirements-test.txt
Ran below CI builds
- Both PR tester is fine
- Nightly is fine - `fledge_nightly_build_ub2004/1400/`
- One custom bucket API tests - `fledge_wl_bucket_service_api/244/`
And now python tests are running fine
Note: Removed temporary fix at Ub20 PR tester;
=> FOGL-8917 setuptools pip dep fixes when python version is greater than 3.8

tests/system/python/api/test_statistics.py
The test scenario has been failing intermittently on platforms since the FOGL-8788 merge. Instead of adding an extra wait after the stats history request call to check the READINGS stats count, implemented a consistent 15-second wait for the schedule to ensure it runs before the stats history call.
ran custom Ci Jobs:
```
ub18 + postgres - Build 850 - **PASSED**
ub20 + sqlite - Build 71 -  **PASSED**
centos stream9 + sqlite - Build 729 - **PASSED**
```
=> FOGL-9163 API statistics schedule wait time fixes in tests

python/fledge/services/core/api/package_log.py, python/fledge/services/core/support.py, tests/unit/python/fledge/services/core/api/test_package_log.py
**Sample content of logs directory inside support bundle**
```
$ tree logs/
logs/
├── debug-trace
│   ├── omf.log
│   └── s2opcua.log
├── package
│   ├── 241122-05-58-14-list.log
│   ├── 241122-05-58-20-list.log
│   ├── 241122-05-58-21-fledge-south-s2opcua-install.log
│   ├── 241122-05-58-42-list.log
│   ├── 241122-05-58-49-list.log
│   ├── 241122-05-58-51-fledge-north-opcuaclient-install.log
│   ├── 241122-06-09-47-list.log
│   ├── 241122-06-10-05-list.log
│   └── 241122-06-10-06-fledge-filter-python35-install.log
└── sys
├── fl_syslog.log
├── fl_syslog_factor
├── fl_syslog_script_runs
├── syslog-241122-08-12-26
├── syslog-S2-241122-08-12-26
└── syslogStorage-241122-08-12-26
3 directories, 27 files
```
As per **FLEDGE_DATA**:
debug-trace - All log files will be listed as is
package - All …
=> FOGL-9265 - Debug trace logs directory added to support bundle

python/fledge/services/core/support.py
**Sample content**
```
$ ls support-241125-07-13-56/logs/sys
fl_syslog.log			fl_syslog_script_runs		syslog-OMF-241125-07-13-56 syslog-SP-241125-07-13-56     syslog-KP-241125-07-13-56	syslog-RW-241125-07-13-56
fl_syslog_factor		syslog-241125-07-13-56	syslog-NS-241125-07-13-56	syslogStorage-241125-07-13-56
```
where,
prefix fl meant related for => utility logs
syslog -KP => dispatcher Service
syslog -NS => notification Service
syslog -SP => North Service
syslog-OMF => North Task
syslog -RW => South Service
syslogStorage => Storage Service
syslog => combined logs
=> FOGL-4015 individual external services logs added in support bundle

tests/system/python/e2e/test_e2e_modbus_c_pi.py, tests/system/python/e2e/test_e2e_modbus_c_rtu_pi.py
https://github.com/fledge-iot/fledge/pull/1495/files#r1861987481
Custom Job run available at - `fledge_on_demand_code_coverage_ub2004/97/` - now modbus pi one is now passing
TestE2eCsvMultiFltrPi setup will be fixed by FOGL-9297 changes
TestE2EKafka seems to be flaky one; most likely destination server is NOT responding/available
=> FOGL-9252.patch task name fixes in modbus E2E tests

python/fledge/common/configuration_manager.py, tests/unit/python/fledge/common/test_configuration_manager.py
Here is the custom build run - `fledge_on_demand_code_coverage_ub2004/96/#showFailuresLink`
~`e2e.test_e2e_modbus_c_pi.TestE2EModbusCPI.test_end_to_end ` test failure due to some other reason which is a incomplete change made in [PR](https://github.com/fledge-iot/fledge/pull/1495/files#r1861987481)~ Now fixed
And other failures  seems to be flaky one's
Latest run - `fledge_on_demand_code_coverage_ub2004/100/#showFailuresLink`
=> FOGL-9297 - Configuration Manager fixes for optional attribute when cleaning up the values

C/common/config_category.cpp, C/common/include/config_category.h
Configuration support for optional attributes, such as keyName and keyDescription, in the kvlist for the C++
=> FOGL-9311 - Add  properties to key/value lists in C++

C/common/config_category.cpp, C/common/include/config_category.h, docs/plugin_developers_guide/02_writing_plugins.rst, python/fledge/common/configuration_manager.py, tests/unit/python/fledge/common/test_configuration_manager.py
**The representation of a configuration item can be as follows**
```
{
"description": "The datapoints that represent our modelled asset",
"type": "kvlist",
"order": "3",
"displayName": "Datapoints",
"properties": {
"asset": {
"description": "The asset name to fetch the data from",
"displayName": "Source Asset",
"type": "string",
"default": ""
},
"datapoint": {
"description": "The datapoint to fetch the data from within the asset",
"displayName": "Source Datapoint",
"type": "string",
"default": ""
},
"type": {
"description": "The type of the datapoint to create in the model asset",
"displayName": "Type",
"type": "enumeration",
"options": [
"float",
"integer",
"string"
],
"default": "float"
},
"default": {
"description": "Default value for the item in the model",
"displayName": "Default", …
```
=> FOGL-9312 - Add properties to key/value list in Python

C/services/north/data_load.cpp
The stack trace below shows the thread responsible for updating the `last_object` to an incorrect value:
```
0# DataLoad::flushLastSentId() at /usr/include/boost/stacktrace/stacktrace.hpp:213
1# DataLoad::readBlock(unsigned int) at /home/ashwini/WL-develop/FogLAMP/C/services/north/data_load.cpp:250
2# DataLoad::loadThread() at /home/ashwini/WL-develop/FogLAMP/C/services/north/data_load.cpp:133
3# 0x00007F515788BDF4 in /lib/x86_64-linux-gnu/libstdc++.so.6
4# 0x00007F5157EF7609 in /lib/x86_64-linux-gnu/libpthread.so.0
5# clone in /lib/x86_64-linux-gnu/libc.so.6
```
The function `DataLoad::readBlock()` sets the `last_object` marker of the stream to `lastFetchedId`. When the outbound connection for the north plugin is down, the readings remain in the stream. If we disable the plugin, the …
=> FOGL-9343 Inconsistent update of 'last_object' field of streams table

python/fledge/common/configuration_manager.py, tests/unit/python/fledge/common/test_configuration_manager.py
As per JIRA, no API validation is required for the schema itself. The API only checks that if a schema is provided, it cannot be empty and its type must be an object.
**Sample Output**
```
{
"description": "Test JSON schema",
"type": "JSON",
"default": "{ \"name\": \"AJ\" }",
"schema": {
"type": "object",
"properties": {
"name": {
"type": "string"
},
"age": {
"type": "integer"
}
},
"required": [
"name"
]
},
"order": "4",
"value": "{ \"name\": \"AJ\" }"
}
```
Note: _schema_ is an object type
=> FOGL-9316 Optional attribute schema support has been added to the core configuration manager for JSON items

C/common/JSONPath.cpp, C/common/datapoint.cpp, C/common/include/reading.h, C/common/pythonreading.cpp, C/common/readingset_circularbuffer.cpp, tests/unit/C/common/test_circular_buffer.cpp, tests/unit/C/common/test_imageencode.cpp, tests/unit/C/common/test_python_reading.cpp, tests/unit/C/common/test_python_reading_set.cpp, tests/unit/C/common/test_python_readingnumpy.cpp, tests/unit/C/common/test_reading_array.cpp
One definite leak left, in the unit test code where I catches an exception which is a pointer
==2576541== LEAK SUMMARY:
==2576541==    definitely lost: 1,600 bytes in 200 blocks
==2576541==    indirectly lost: 0 bytes in 0 blocks
==2576541==      possibly lost: 190,584 bytes in 149 blocks
==2576541==    still reachable: 14,528,263 bytes in 4,576 blocks
==2576541==         suppressed: 0 bytes in 0 blocks
`TEST(Categorytest, parseError)
{
EXPECT_THROW(ConfigCategory("parseTest", json_parse_error), ConfigMalformed*);
}`
This is not usually an issue, but due to the way GTEST is picking up the exception there is no way to free the exception class.
Fixed leaks in ReadingSetCircularBuffer, 2D datapoint arrays, caused by non-virtual Reading destructor, PythonNumpy  issue and Image Encoding.
There …
=> FOGL-9653 Fix memory leaks in C/common unit tests and library

C/common/include/logger.h, C/common/logger.cpp, C/services/storage/storage.cpp, C/tasks/check_updates/check_updates.cpp, C/tasks/check_updates/main.cpp, C/tasks/purge_system/main.cpp, C/tasks/purge_system/purge_system.cpp, C/tasks/statistics_history/main.cpp
A number of things have been done
- Allow only a single instance to be created
- Delay the creation of the worker thread until the first intercepter requires it - reduced overhead if no intercepters are registered
- Protect the deletion of the Logger class
- Clean up tasks that created multiple Logger
- Added missing Doxygen comments
- Cleaned up the printLogString entry point and enabled use at different log levels
=> FOGL-9770 Updates to Logger class

python/fledge/services/core/server.py
Used `gather` tasks for clean, parallel async execution when you want all tasks to finish and don’t need complex control.
=> FOGL-9520 smooth termination or shutdown of the microservice across all compatible Python versions that we have supported to date

C/plugins/north/OMF/omf.cpp, C/plugins/north/OMF/plugin.cpp, docs/OMF.rst, docs/troubleshooting_pi-server_integration.rst
Support for Static Data values for Linked Types was added in [FOGL-9056](https://scaledb.atlassian.net/browse/[FOGL-9056](https://scaledb.atlassian.net/browse/FOGL-9056)). Static Data values become AF Attribute Templates in the AF Template _FledgeAsset_. Upgrading existing Fledge systems failed because OMF North would attempt to define _FledgeAsset_ with Static Data values that did not exist before. This resulted in OMF HTTP 409 (Conflict) which would stop all processing until "unstable" PI was corrected. This has been fixed. If creation of _FledgeAsset_ results in HTTP 409, OMF North will write the message "_FledgeAsset Type exists with a different definition_" and continue processing normally.
Sending Static Data in later OMF Data messages is benign. Static Data properties that do not …
=> FOGL-9792: FledgeAsset Type mismatch error when Static Data properties change

C/common/include/logger.h, C/common/logger.cpp, python/fledge/common/logger.py, scripts/common/write_log.sh
1. **Added support for logging messages to a remote syslog via UDP protocol.**
The logging system initializes a UDP socket (m_UdpSockFD) and sends log messages to a remote server defined by environment variables.
1. **Environment Variables:**
Introduced the following environment variables for dynamic configuration:
**SYSLOG_UDP_ENABLED:** Enables or disables UDP logging. If set to true, logs are sent to the configured UDP sink.
**LOG_IP:** Specifies the IP address of the remote logging server. Defaults to 127.0.0.1 if not set.
**LOG_PORT:** Specifies the port number for the remote logging server. Defaults to 5140 if not set.
The environment variables allow customization without requiring code changes, making the system adaptable to different deployment environments
=> FOGL-9746 implementation of Remote UDP Logging for syslog

C/plugins/common/include/http_sender.h, C/plugins/common/include/libcurl_https.h, C/plugins/common/include/piwebapi.h, C/plugins/common/include/simple_http.h, C/plugins/common/include/simple_https.h, C/plugins/north/OMF/include/ocs.h, C/plugins/north/OMF/include/omfinfo.h, C/plugins/north/OMF/ocs.cpp, C/plugins/north/OMF/omfinfo.cpp
OMF North had a mechanism for confirming the connection to PI Web API every 60 seconds. This work adds equivalent connectivity checks for AVEVA Data Hub and Edge Data Store.
=> FOGL-9390: OMF North: added periodic connectivity check for ADH and EDS

C/plugins/north/OMF/omf.cpp, docs/troubleshooting_pi-server_integration.rst
OMF error message is "*An existing LINK includes an AF Attribute that overlaps with the name of an AF Attribute that would be created for the specified LINK*." This means that an OMF Data message for Linked Types is attempting to create an AF Attribute with the same name as an existing attribute.
OMF does not report the name of the conflicting AF Attribute. To help with troubleshooting, OMF North now logs the links that were attempted if the OMF Data message fails. The [Troubleshooting the PI Server Integration](https://github.com/fledge-iot/fledge/blob/develop/docs/troubleshooting_pi-server_integration.rst) page has been updated with a detailed explanation.
OMF North does not log the Links created if there are no errors because the OMF Data messages are often large. It is expensive to …
=> FOGL-9845: OMF North reports AF Attribute name conflict when creating OMF Links

python/fledge/services/core/server.py
Problem with Python 3.12 and aiohttp 3.10.11 specific resolution: wait_closed() hang indefinitely or block for minutes when there are active connections.
Therefore, we addressed the asyncio timeout exception to ensure a forced restart in such scenarios. As we approach the release, I have refrained from modifying the aiohttp specific release version, as this stable version encompasses our functionality and includes the necessary test dependencies.
=> FOGL-9981 Fledge restart and shutdown fixes
