fledge-iot/fledge

tests/system/python/packages/test_available_and_install_api.py
=> FOGL-3571 Fix merge conflicts

tests/system/python/packages/data/readings35.py, tests/system/python/packages/test_filters.py, tests/system/python/scripts/package/remove, tests/system/python/scripts/package/reset
**Notes**: All Changes verified on fledge CI as well
=> FOGL-3576 resolved foglamp text occurrences

scripts/plugins/storage/postgres/downgrade/31.sql, scripts/plugins/storage/postgres/upgrade/32.sql, tests/system/python/packages/test_authentication.py, tests/system/python/packages/test_gcp_gateway.py, tests/unit/C/common/test_string_utils.cpp
**Note** - I have checked in north-gcp tests system file (as it's forward merge). We should disable this test on CI until we get this repo available on Fledge organization.
=> textual fixes

python/fledge/services/core/api/plugins/remove.py
Signed-off-by: rajeshkumar426 <rajeshkumar426@outlook.com>
=> FOGL-3718_patch.3 Added removal endpoint support for make install

tests/system/python/api/test_audit.py
Signed-off-by: rajeshkumar426 <rajeshkumar426@outlook.com>
=> FOGL-3812 Added PKGRM audit log

C/plugins/common/omf.cpp
build on Centos 7:
Execution on Ubuntu 18 and on Centos 7:
=> FOGL-3824: FIXED - make is failing on RPM platform with develop branch of fledge code

tests/unit/python/fledge/common/test_configuration_manager.py
=> unit test improvements w.r.t FOGL-3796 changes

C/plugins/storage/sqlite/common/include/connection.h, C/plugins/storage/sqlite/common/readings.cpp, C/plugins/storage/sqlite/plugin.cpp, C/plugins/storage/sqlitememory/connection.cpp, C/plugins/storage/sqlitememory/plugin.cpp, python/fledge/tasks/purge/purge.py
rather than uderlying storage bytes
=> FOGL-1301 Reinstate purge by size with the size modified to be row count

C/plugins/common/omf.cpp
problems fixed, stored the hierarchy id in the plugin_data table
=> FOGL-3849: Reconfiguration is not working properly in North task (PI Web API)

C/plugins/common/include/http_sender.h, C/plugins/common/include/libcurl_https.h, C/plugins/common/include/ocs.h, C/plugins/common/include/omf.h, C/plugins/common/include/simple_http.h, C/plugins/common/include/simple_https.h, C/plugins/common/libcurl_https.cpp, C/plugins/common/ocs.cpp, C/plugins/common/omf.cpp, C/plugins/common/simple_http.cpp, C/plugins/common/simple_https.cpp, C/plugins/north/PI_Server_V2/plugin.cpp, CMakeLists.txt, README.rst
Work in progress
Tested on:
* Ubuntu 18
* Buster
* Centos - the OCS integration doesn't work
OCS:
PiWEB API:
CR:
=> FOGL-3427:  Implement the OCS connectivity in the PI_Server plugin allowing the user to select the proper Endpoint

C/plugins/storage/sqlite/common/readings.cpp
=> FOGL-3872 Fix issue if the delete block size was greater than the number

scripts/plugins/storage/postgres/downgrade/33.sql, scripts/plugins/storage/postgres/upgrade/34.sql, scripts/plugins/storage/sqlite/upgrade/34.sql
=> FOGL-3913 Upgrade/Downgrade scripts added for Postgres engine with foglamp_schema 34

tests/unit/C/plugins/common/test_omf_translation_piwebapi.cpp
=> FOGL-3898: C++ unit tests fixed

python/fledge/services/core/server.py
=> FOGL-3930: fix the issue at the foglamp restart

python/fledge/services/core/support.py
=> FOGL-3932 Add statistics history and service syslogs to the support

docs/92_downloads.rst
=> Update download header and text to be more generic regarding Linux

python/fledge/services/core/api/support.py, tests/unit/python/fledge/services/core/api/test_support.py
**curl example**
```
$ curl -sX GET "http://localhost:8081/fledge/syslog?source=Sine%20%231" | jq
{
"logs": [
"Apr 23 18:11:20 aj Fledge Sine #1[13954] ERROR: sinusoid: module.name: Sinusoid plugin_init: module.name#012NoneType: None\n",
"Apr 23 18:15:50 aj Fledge Sine #1[15928] ERROR: sinusoid: module.name: Sinusoid plugin_init: module.name#012NoneType: None\n"
],
"count": 2
}
$ curl -sX GET "http://localhost:8081/fledge/syslog?source=Sine%201" | jq
{
"logs": [
"Apr 23 18:30:21 aj Fledge Sine 1[21288] ERROR: sinusoid: module.name: Sinusoid plugin_init: module.name#012NoneType: None\n"
],
"count": 1
}
$ curl -sX GET "http://localhost:8081/fledge/syslog?source=HT&level=info" | jq
{
"logs": [
"Apr 23 19:09:51 aj Fledge HT[16446] INFO: …
```
=> FOGL-3826 support added for service & task name filteration in syslogs API

C/common/include/logger.h, C/common/logger.cpp
=> FOGL-3981 Make sure the applcation name we give to syslog always starts

docs/plugin_developers_guide/05_storage_plugins.rst
=> FOGL-4022 Add SQLite In Memory documentation and document storage.json

README.rst
=> FOGL-4027 misspelled fixes

C/plugins/storage/postgres/connection.cpp, C/plugins/storage/postgres/include/connection.h
exception on CentOS platforms.
=> FOGL-4050 Remove use of regex in postgress plugin as this causes an

docs/KERBEROS.rst, docs/REDHAT.rst
=> FOGL-4042 UPdate documentation

tests/system/python/api/test_statistics.py
*among default scheduled stats history runs
=> FOGL-3853 Fixed test for finding stats history entry for an asset 

python/fledge/services/core/support.py
=> FOGL-4107 Add plugin data and streams table to support bundle

C/plugins/north/OMF/plugin.cpp
```
WARNING: OMF plugin: current element 'asset1' doesn't have 'dataTypesShort' property, calculated '0x10203'
WARNING: OMF plugin: current element 'asset2' doesn't have 'dataTypesShort' property, calculated '0x202'
```
Original
```
{"sentDataTypes":[{"asset1":{"type-id":5,"dataTypesShort":"0x10203","dataTypes":{"p1":{"type":"number","format":"float64"},"p2":{"type":"number","format":"float64"},"p3":{"type":"string"}}}},{"asset2":{"type-id":5,"dataTypesShort":"0x202","dataTypes":{"p1":{"type":"number","format":"float64"},"p2":{"type":"number","format":"float64"}}}}]}
```
Forced update
```
{"sentDataTypes":[{"asset1":{"type-id":5,"dataTypes":{"p1":{"type":"number","format":"float64"},"p2":{"type":"number","format":"float64"},"p3":{"type":"string"}}}},{"asset2":{"type-id":5,"dataTypes":{"p1" …
```
=> Fogl 4111: calculate the dataTypesShort if missed in the plugin_data

C/plugins/common/include/omf.h, C/plugins/common/omf.cpp
=> FOGL-4090: fix the handling of the global type id/type id in case of errors

docs/92_downloads.rst, docs/quick_start.rst
=> Correct where the download link points.

docs/92_downloads.rst, docs/REDHAT.rst, docs/quick_start.rst
* Correct where the download link points.
* Fix to point to latest not master
=> Master (1.8.0) - Correct where the download link points. (#100)

tests/system/python/packages/test_eds.py
=> System test for EDS

python/fledge/tasks/purge/purge.py, tests/unit/python/fledge/tasks/purge/test_purge.py
It works only with Sqlite Engine. And For Postgres engine same issue reported in FOGL-4102
=> FOGL-4173 statistics history & audit trail logs table deletion added on purge task

python/fledge/common/configuration_manager.py, tests/unit/python/fledge/common/test_configuration_manager.py
=> more unit tests added for configuration manager w.r.t optional mandatory attribute

C/plugins/common/omf.cpp, C/plugins/north/OMF/plugin.cpp, C/tasks/north/sending_process/sending.cpp
=> FOGL-2919: implements the no blocking error handling for Pi Web API and changes the blockSize to 500

docs/plugin_developers_guide/04_north_plugins.rst
as it disturbed when white-labelled
=> doc-lint fixes for north plugins with list table directive

C/plugins/storage/sqlite/common/connection.cpp
=> FOGL-4249: do not apply the full algorithm id the date is in specific cases

C/services/south/ingest.cpp
=> FOGL-4250 Minor performance improvement in ingest code

docs/scripts/plugin_documentation
**Note:**
1. In future we may need to checkout git repositories based on tag.
2. After this Pull Request gets merged into develop, we need to change DOCBRANCH value from 1.8.1RC to develop
=> Fixed the script to avoid building docs from the develop

docs/scripts/plugin_documentation
=> Replaced DOCBRANCH from 1.8.1RC to develop

python/fledge/common/service_record.py
=> management type support added in service registry

python/fledge/plugins/common/utils.py
=> FOGL-4234 Fix incorrect bit definition for deprecated plugins

tests/system/python/packages/test_available_and_install_api.py
=> strict length check for available service package has removed

scripts/fledge
=> FOGL-4325 python services output append to status command

C/services/storage/configuration.cpp
=> FOGL-4286 Fix display of reading plugin

C/services/storage/configuration.cpp, C/services/storage/include/storage_plugin.h, C/services/storage/storage.cpp, C/services/storage/storage_plugin.cpp, tests/unit/C/services/storage/postgres/etc/storage.json
=> FOGL-4381 Call storage plugin shutdown when the storage service is

python/fledge/services/core/api/scheduler.py, tests/unit/python/fledge/services/core/api/test_scheduler_api.py
=> FOGL-4441 POST scheduled_process fixes along with their unit tests

C/plugins/common/include/libcurl_https.h, C/plugins/common/include/simple_http.h, C/plugins/common/include/simple_https.h, C/plugins/common/libcurl_https.cpp, C/plugins/common/simple_http.cpp, C/plugins/common/simple_https.cpp
=> FOGL-4366 Add mechanism to log OMF messages

C/plugins/common/omf.cpp, C/plugins/storage/sqlite/CMakeLists.txt, C/plugins/storage/sqlite/common/connection.cpp, C/plugins/storage/sqlite/common/connection_manager.cpp, C/plugins/storage/sqlite/common/include/connection.h, C/plugins/storage/sqlite/common/include/connection_manager.h, C/plugins/storage/sqlite/common/readings.cpp, C/plugins/storage/sqlite/plugin.cpp, C/plugins/storage/sqlitememory/connection.cpp, C/services/storage/storage.cpp, CMakeLists.txt, scripts/plugins/storage/sqlite.sh, scripts/plugins/storage/sqlite/init_readings.sql, tests/unit/C/services/storage/sqlite/testSetup.sh
Attach, improved error handling:
*C units tests*
Ubuntu 01:
R4, the 3 failing are related to the averages calculation:
up to 8 dbs tested, 2 tables each:
attach at the foglamp restart:
post / fetch data:
=> FOGL-3596: multi db

python/fledge/services/core/api/scheduler.py, tests/unit/python/fledge/services/core/api/test_scheduler_api.py
System/Unit tests results available at `{CI_BASE_URI}/Fledge%20Nightly%20Jobs/job/fledge_nightly_build_ub1804/304/`
=> FOGL-4412 Duplicate name entry restricted in POST schedule API

python/fledge/services/core/api/plugins/remove.py
=> FOGL-4463 dpkg query fix for remove API

scripts/fledge
=> FOGL-4543: /usr/local/lib path added in LD_LIBRARY_PATH env

C/services/storage/storage.cpp
=> FOGL-4451 Fixed issue with error when makign child of Advanced category

C/plugins/north/OMF/include/OMFHint.h, C/plugins/north/OMF/omf.cpp, C/plugins/north/OMF/omfhints.cpp
=> Fogl 4367: implements integer OMF hint and fix Datapoint

docs/scripts/plugin_documentation
=> FOGL-4256 Use current branch as branch for plugin documentation

CONTRIBUTING.md
=> FOGL-4575 Add procedure for reporting securioty vulnerabilities

C/plugins/storage/sqlite/common/readings.cpp
- the error is logged If it is not possible to attach a new DB and the row is skipped/not stored.
```
user.err, 3,1,Sep 24 09:55:02,localhost,Fledge, Storage[21530]: ERROR: attachNewDb - It was not possible to attach the db :/home/foglamp/Development/fledge/data/readings_10.db: to an idle connection, error :too many attached databases - max 10:
user.warning, 4,1,Sep 24 09:55:02,localhost,Fledge, Storage[21530]: WARNING: appendReadings - It was not possible to insert the row for the asset_code :perf_2_a133: into the readings, row ignored.
user.err, 3,1,Sep 24 09:55:02,localhost,Fledge, Storage[21530]: ERROR: attachNewDb - It was not possible to attach the db :/home/foglamp/Development/fledge/data/readings_10.db: to an idle connection, error :too many attached databases - max 10: …
```
=> Fogl 4546 : Asset entry not getting stored in db when number of assets are more than 135

C/plugins/storage/sqlite/plugin.cpp, C/services/storage/include/plugin_configuration.h, C/services/storage/include/storage_plugin.h, C/services/storage/include/storage_service.h, C/services/storage/pluginconfiguration.cpp, C/services/storage/storage.cpp, C/services/storage/storage_plugin.cpp, C/services/storage/stream_handler.cpp
=> FOGL-4290 Add configuration for storage plugins

python/fledge/services/core/api/plugins/remove.py, tests/unit/python/fledge/services/core/api/plugins/test_remove.py
=> FOGL-4599 Plugin remove unit tests coverage added

python/fledge/services/core/api/plugins/update.py, tests/unit/python/fledge/services/core/api/plugins/test_update.py
=> FOGL-4598 update plugin unit tests coverage added

tests/system/python/api/test_audit.py, tests/system/python/api/test_configuration.py
Note : Once FOGL-4604 is resolved we may need to fix the tests accordingly.
=> FOGL-4596: Fixes required in api tests after changes of FOGL-4290

C/common/JSONPath.cpp
=> FOGL-4620 Add missing header file

C/services/storage/storage.cpp
=> FOGL-4604 Add description to category creation

tests/system/python/packages/test_available_and_install_api.py
**CI System test health**
**Edit** After Feedback fixes: Next run on CI
=> FOGL-4613 Plugin/Service package installation system tests updated as per FOGL-4347

C/common/config_category.cpp, C/common/include/config_category.h
=> FOGL-4568 Add ability to set values in a configuration category

C/plugins/common/include/piwebapi.h, C/plugins/common/piwebapi.cpp, C/plugins/north/OMF/omf.cpp, C/plugins/north/OMF/plugin.cpp, C/plugins/storage/sqlite/common/readings.cpp
=> FOGL-4548: feature implemented / bug fixed

docs/plugin_developers_guide/06_filter_plugins.rst, docs/plugin_developers_guide/index.rst
=> FOGL-4670 Add filter plugin section to developers guide

docs/plugin_developers_guide/08_notify_plugins.rst, docs/plugin_developers_guide/index.rst
=> FOGL-4702 Add notification delivery plugin developers guide

C/plugins/storage/sqlite/common/connection.cpp, C/plugins/storage/sqlite/common/connection_manager.cpp, C/plugins/storage/sqlite/common/include/connection.h, C/plugins/storage/sqlite/common/include/connection_manager.h, C/plugins/storage/sqlite/common/readings.cpp, C/plugins/storage/sqlite/plugin.cpp, CMakeLists.txt, VERSION, scripts/plugins/storage/sqlite/init_readings.sql, scripts/plugins/storage/sqlite/upgrade/36.sql, tests/unit/C/services/storage/sqlite/plugin_cfg/sqlite/etc/storage.json
**C unit tests passed:**
**System tests passed:** 
**upgrade:**
ok
=> Fogl 4592: Multiple readings dbs/tables: investigating on errors reported by Yash

docs/KERBEROS.rst, docs/OMF.rst, docs/RASPBIAN.rst, docs/plugin_developers_guide/06_filter_plugins.rst, docs/plugin_developers_guide/08_notify_plugins.rst, docs/plugin_developers_guide/10_testing.rst, docs/plugin_index.rst, docs/processing_data.rst
=> North OMF doctree fixes and other typos/warning fixes

Makefile
=> FOGL-4734:  debug option removed

docs/plugin_index.rst, docs/scripts/plugin_documentation
https://fledge-iot.readthedocs.io/en/fogl-4725
=> FOGL-4725 DOCBRANCH fixes for plugin documentation build on RTD

C/plugins/storage/sqlite/common/connection.cpp, C/services/storage/storage.cpp
=> FOGL-4775 Fix overflow issue that caused rapidjson to SIGABORT

C/services/common/include/plugin_api.h
FOGL-4498: added builtin plugin option SP_BUILTIN = 0x0080
Moved deprecated to 0x1000
=> FOGL-4498: added builtin plugin option SP_BUILTIN

tests/system/python/api/test_notification.py
=> System test fixes as per FOGL-4498 changes

C/plugins/storage/sqlite/common/connection.cpp
=> FOGL-4776 Fix RPi compile issue

C/plugins/north/OMF/plugin.cpp
=> Added SP_BUILTIN flag

requirements.sh
parameters changed:
-DSQLITE_MAX_ATTACHED=62 
-DSQLITE_MAX_COMPOUND_SELECT=900
> A compound SELECT statement is two or more SELECT statements connected by operators UNION, UNION ALL, EXCEPT, or INTERSECT. We call each individual SELECT statement within a compound SELECT a "term"
> 
> https://www.sqlite.org/limits.html
> 
Tested using multi readings (different temporary branch):
files created:
605 assets created - 41 databases used:
15|40|bench_1_asset_600
1|41|bench_2_asset_1
2|41|bench_2_asset_2
3|41|bench_2_asset_3
4|41|bench_2_asset_4
5|41|bench_2_asset_5
assets on GUI:
Tested from deb pkgs - 600 assets
```
5|40|bench_3_asset196
6|40|bench_3_asset197
7|40|bench_1_asset198
8|40|bench_1_asset199
9|40|bench_1_asset200
10|40|bench_2_asset198
11|40|bench_2_asset199
12|40|bench_2_asset200 …
```
=> Fogl 4706: tight sqlite3 (build from sources) to fledge for Ubuntu also

scripts/plugins/storage/postgres/downgrade/37.sql, scripts/plugins/storage/postgres/upgrade/38.sql
=> FOGL-4799: fix Postgress upgrade

scripts/plugins/storage/sqlite/upgrade/35.sh, scripts/plugins/storage/sqlite/upgrade/38.sh
=> FOGL-4798: avoid too many debug messages

C/plugins/storage/sqlite/common/connection.cpp, C/plugins/storage/sqlite/common/include/connection.h, C/plugins/storage/sqlite/common/include/readings_catalogue.h, C/plugins/storage/sqlite/common/readings.cpp, C/plugins/storage/sqlite/common/readings_catalogue.cpp
=> FOGL-4803: solves the issue FOGL-4803

tests/system/python/packages/test_available_and_install_api.py
=> FOGL-4800 service installed assertion fixes; as now by default 3 services will appear with fresh setup

python/fledge/plugins/north/common/common.py, python/fledge/tasks/north/sending_process.py
CI - E2E tests passed `Fledge%20Nightly%20Jobs/job/fledge_nightly_build_ub1804/469/`
=> FOGL-4757 nested JSON handling in python north task

python/fledge/services/core/api/north.py
```
$ ./scripts/fledge status
Fledge v1.8.2 running.
Fledge Uptime:  4336 seconds.
Fledge records: 38 read, 76 sent, 0 purged.
fledge.services.storage --address=0.0.0.0 --port=42813
fledge.services.north --port=42813 --address=127.0.0.1 --name=OMF-Service 
fledge.services.north --port=42813 --address=127.0.0.1 --name=HTC-Service 
=== Fledge tasks:
tasks/sending_process --port=42813 --address=127.0.0.1 --name=HTC-task 
tasks/sending_process --port=42813 --address=127.0.0.1 --name=OMF-task
// 20201218151836
// http://localhost:8081/fledge/north
[
{
"id": "7a2b5808-7838-49b9-b91e-18ebe6926f51",
"name": "HTC-Service",
"processName": "north_C",
"enabled": true, …
```
=> FOGL-4794 north API enhancements added as per service/task execution

python/fledge/services/core/api/support.py, tests/unit/python/fledge/services/core/api/test_support.py
Notes:
```
Info & Above => info | warning | error | fatal
Warning & Above => warning | error | fatal
Error & Above => error | fatal
debug => all
```
=> FOGL-4814 syslog API enhancements

Makefile
=> FOGL-4842 north_C missing script added when make install

python/fledge/common/iprpc.py, python/fledge/common/utils.py
Some clean up and a fix of small issue occured when importing eprint.
=> Fogl 4524.patch

python/fledge/services/core/api/notification.py
FOGL-4852: : Not getting correct "Retrigger time" in notification creation
=> FOGL-4852: Not getting modified "retrigger_time" in POST

tests/system/python/api/test_common.py, tests/unit/python/fledge/services/core/api/test_common_ping.py
=> FOGL-3921 semantic versioning assertion added for ping

C/services/north/north.cpp
=> FOGL-4843 Make sure the description is added to the configuration

python/fledge/services/core/api/notification.py, tests/unit/python/fledge/services/core/api/test_notification.py
FOGL-4865: retrigger_time in GET / PUT API endpoints
=> FOGL-4865: retrigger_time in GET / PUT API endpoints

C/plugins/north/OMF/omfhints.cpp
=> FOGL-4678: fix implemented

C/plugins/north/OMF/include/omf.h, C/plugins/north/OMF/omf.cpp, C/plugins/north/OMF/plugin.cpp
=> FOGL-4668: sendFullStructure implementation

C/plugins/north/OMF/plugin.cpp
=> FOGL-4949: fix OMF cfg

scripts/plugins/storage/sqlite.sh
=> FOGL-4962 SQLite does not support managed storage

python/fledge/services/core/api/north.py
=> FOGL-4961 Disable north service disappears after restart issue fixes in  north API

C/plugins/north/OMF/include/omf.h
=> FOGL-4972: fix raspberry

VERSION, scripts/plugins/storage/postgres/downgrade/39.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/40.sql, scripts/plugins/storage/sqlite/downgrade/39.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/40.sql
@sstefano69 I still need to do SQLite, and I have doubts about that. But in order to let Sebastian move forward can you see a problem with this?
=> Increase size of asset_code in Postgres database

VERSION, scripts/plugins/storage/postgres/downgrade/39.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/40.sql, scripts/plugins/storage/sqlite/downgrade/39.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/40.sql
* Increase size of asset_code in Postgres database
* SQLite requires no action
=> Increase size of asset_code in Postgres database (#277)

python/fledge/common/iprpc.py
. clean up spacing
. in serve, handle EOF and exception on initial read separately for more graceful exit/management
. handle SystemExit for when server is bailing
. method getattr, make argument optional
=> update from foglamp bad bearing code

C/common/json_utils.cpp
=> Fix escaping of escaped double quote characters

C/plugins/storage/sqlite/common/include/readings_catalogue.h, C/plugins/storage/sqlite/common/readings.cpp, C/plugins/storage/sqlite/common/readings_catalogue.cpp
Fogl 5001: fix purge - "Retain Unsent Data" not working as expected
=> cherry-picked FOGL-5001 to 1.9.0RC

C/common/include/filter_pipeline.h, C/tasks/north/sending_process/north_filter_pipeline.cpp, C/tasks/north/sending_process/sending_process.cpp
FOGL-5035: allow some time for filter pipeline setup
=> FOGL-5035: allow some time for filter pipeline setup

C/plugins/storage/sqlite/common/include/connection.h, C/plugins/storage/sqlite/common/readings.cpp, C/plugins/storage/sqlite/plugin.cpp
```
Feb 19 09:15:43 ubuntu01 Fledge Storage[1085]: DEBUG: xxx appendReadings - thread Id :139877546977024: operation started , threads count :2:
Feb 19 09:15:43 ubuntu01 Fledge Storage[1085]: DEBUG: xxx appendReadings - thread Id :139877517707008: operation started , threads count :4:
Feb 19 09:15:43 ubuntu01 Fledge Storage[1085]: DEBUG: xxx shutdownAppendReadings - thread Id :139877694158720: appendReadings shutting down started
Feb 19 09:15:43 ubuntu01 Fledge Storage[1085]: DEBUG: xxx shutdownAppendReadings - thread Id :139877694158720: waiting threads to shut down, count :4:
Feb 19 09:15:43 ubuntu01 Fledge Storage[1085]: DEBUG: xxx shutdownAppendReadings - thread Id :139877694158720: waiting threads to shut down, count :3:
Feb 19 09:15:43 …
```
=> FOGL-5038:  synchronization mechanism in the sqlite plugin shutdown

C/services/common-plugin-interfaces/python/include/python_plugin_common_interface.h, C/services/common-plugin-interfaces/python/pyobject_reading_parser.cpp, C/services/common/include/north_python_plugin_handle.h, C/services/common/north_python_plugin_handle.cpp, C/services/common/plugin_manager.cpp, C/services/filter-plugin-interfaces/python/python_plugin_interface.cpp, C/services/north-plugin-interfaces/python/CMakeLists.txt, C/services/north-plugin-interfaces/python/python_plugin_interface.cpp, C/services/north/include/north_plugin.h, CMakeLists.txt, python/fledge/plugins/common/shim/north_shim.py
FOGL-5059: Initial implementation
=> FOGL-5049: North service loads Python plugin

C/services/common/include/plugin_api.h, C/services/south/include/south_api.h, C/services/south/include/south_plugin.h, C/services/south/include/south_service.h, C/services/south/south.cpp, C/services/south/south_api.cpp, C/services/south/south_plugin.cpp
As per spec
https://wiki.lfedge.org/display/FLEDGE/Adding+Control+to+Fledge
TODO
- Add security
- Add Python plugin support
=> FOGL-5059 Initial set point control in the south service.

tests/system/python/api/test_service.py
=> FOGL-5079 Fix system test

tests/system/python/api/test_configuration.py
FOGL-4618: fix for api.test_configuration.TestConfiguration
=> FOGL-4618: fix for api.test_configuration.TestConfiguration

scripts/plugins/storage/postgres.sh, scripts/plugins/storage/sqlite.sh, scripts/services/storage
FOGL-5052: create database if missing while restarting the core service
=> FOGL-5052: create database if missing while restarting the core service

C/plugins/north/OMF/omf.cpp
=> FOGL-5118: bug fixed

C/common/include/string_utils.h, C/common/string_utils.cpp, C/plugins/common/include/piwebapi.h, C/plugins/common/piwebapi.cpp, C/plugins/north/OMF/include/omf.h, C/plugins/north/OMF/omf.cpp, CMakeLists.txt, tests/unit/C/common/test_string_utils.cpp, tests/unit/C/plugins/common/test_omf_translation_piwebapi.cpp
**Message substitution**
```
|Failedtosenddata:Noroutetohost| ->
North_Readings_to_PI[20884]: WARNING: Error in retrieving the PIWebAPI version, The PI Web API server is not reachable, verify the network reachability
North_Readings_to_PI[20884]: ERROR: Sending Asset Framework hierarchy, The PI Web API server is not reachable, verify the network reachability - WIN-4M7ODKB0RH2:443 /piwebapi/omf
North_Readings_to_PI[20884]: ERROR: Sending dataType message 'Type', The PI Web API server is not reachable, verify the network reachability - WIN-4M7ODKB0RH2:443 /piwebapi/omf
```
**Message HTTP handling**
```
North_Readings_to_PI[5838]: WARNING: Error in retrieving the PIWebAPI version, 503 Service Unavailable
North_Readings_to_PI[5838]: ERROR: Sending …
```
=> FOGL-4816: improves OMF error log messages 

Makefile
Force use of devtoolset-7 on CentOS 7
=> Force use of devtoolset-7 on CentOS 7

scripts/fledge, scripts/plugins/storage/postgres.sh, scripts/plugins/storage/sqlite.sh
FOGL-5099: addition of purge option
Initial implementation with Sqlite3 storage engine
=> FOGL-5099: addition of purge option

python/fledge/services/core/scheduler/scheduler.py
FOGL-5129, FOGL-5130
FOGL-4413
FOGL-4259 real problem should be fixed.
=> FOGL-4413 / FOGL-5129, FOGL-5130 - fix immediate task execution when scheudle added/enabled

docs/building_fledge/building_fledge.rst, docs/storage.rst
FOGL-4971: documentation to install postgres on CentOS/RHEL
=> FOGL-4971: documentation to install postgres on CentOS/RHEL

VERSION, python/fledge/common/service_record.py, python/fledge/services/core/api/service.py, scripts/fledge, scripts/plugins/storage/postgres/downgrade/40.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/41.sql, scripts/plugins/storage/sqlite/downgrade/40.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/41.sql, scripts/services/dispatcher_c, tests/unit/python/fledge/common/test_service_record.py, tests/unit/python/fledge/services/core/api/test_service.py
**NOTE** - `Fledge%20Nightly%20Jobs/job/fledge_nightly_build_ub1804/610/`
No Regression as such with these changes.
=> FOGL-5139 Dispatcher service API support added

python/fledge/services/core/api/service.py, tests/system/python/api/test_notification.py, tests/unit/python/fledge/services/core/api/test_service.py
**NOTE:** `Fledge%20Nightly%20Jobs/job/fledge_nightly_build_ub1804/613/` - System & unit test health is fine with the changes.
=> FOGL-2746 Error handling in add service when no notification service is installed 

python/fledge/services/core/api/north.py, python/fledge/services/core/api/south.py
**Pending item**
~- [ ] Same fix needs for north API as well.~
**NOTE** - CI is happy with the change. Custom JOB results are available here `{JENKINS_BASE_URI}/Fledge%20Nightly%20Jobs/job/fledge_nightly_build_ub1804/622/#showFailuresLink`
=> FOGL-5199 asset track records & plugin name fixes in south API

tests/system/python/e2e/test_e2e_coap_PI.py, tests/system/python/e2e/test_e2e_expr_pi.py, tests/system/python/e2e/test_e2e_filter_fft_threshold.py, tests/system/python/e2e/test_e2e_vary_asset_http_pi.py
=> Increased wait time for verification of dataSent to north

C/tasks/north/sending_process/sending_process.cpp
=> FOGL-5256: bug fixed

python/fledge/services/core/api/service.py, tests/unit/python/fledge/services/core/api/test_service.py
white-labelled available under `...foglamp/fixes/FOGL-5138/ubuntu1804/x86_64/`
=> FOGL-5138 external mgt service condition added when not installed correctly

python/fledge/common/service_record.py, python/fledge/services/core/server.py, python/fledge/services/core/service_registry/service_registry.py, tests/unit/python/fledge/services/common/microservice_management/test_instance.py, tests/unit/python/fledge/services/core/interest_registry/test_change_callback.py, tests/unit/python/fledge/services/core/service_registry/test_monitor.py, tests/unit/python/fledge/services/core/service_registry/test_service_registry.py, tests/unit/python/fledge/services/core/test_connect.py, tests/unit/python/fledge/services/core/test_server.py
This PR on top of FOGL-5144
**Pending item**
bearer token verification/validation
=> FOGL-5143 Enhance the service registry to issue bearer tokens

C/services/common/CMakeLists.txt, C/services/filter-plugin-interfaces/python/CMakeLists.txt, C/services/filter-plugin-interfaces/python/filter_ingest_pymodule/CMakeLists.txt, C/services/north-plugin-interfaces/python/CMakeLists.txt, C/services/notification-plugin-interfaces/python/CMakeLists.txt, C/services/south-plugin-interfaces/python/CMakeLists.txt, C/services/south-plugin-interfaces/python/async_ingest_pymodule/CMakeLists.txt, tests/unit/C/CMakeLists.txt, tests/unit/C/common/CMakeLists.txt, tests/unit/C/plugins/common/CMakeLists.txt, tests/unit/C/services/core/CMakeLists.txt
=> Conditional execution of Cmake

python/requirements.txt
=> FOGL-5324: Install version of pyjq on basis of python version

docs/securing_fledge.rst
Addition of instructions for self signed certificate authorisation in the browser where the GUI runs
=> Addition of instructions for self signed certificate

tests/system/python/packages/test_authentication.py
=> Updated the tests/system/python/packages/test_authentication.py

.gitignore, scripts/plugins/storage/sqlitelb/init.sql
=> FOGL-5350 users schema changes as made in FOGL-4709 for old style sqlite engine

docs/securing_fledge.rst
=> Revert "Addition of instructions for self signed certificate"

python/fledge/services/core/api/certificate_store.py, tests/unit/python/fledge/services/core/api/test_certificate_store.py
=> FOGL-5385 delete cert store restrictions in API

tests/system/python/packages/test_authentication.py
```
Custom CI Results: will be available at
<JENKINS_BASE_URL>/Fledge%20Custom%20Jobs/job/fledge_packages_system_test_authentication_ub1804/11/
```
All tests are passed now
=> FOGL-5348 Authentication system package tests updated as per FOGL-4709

docs/scripts/fledge_plugin_list, docs/scripts/plugin_documentation
Custom RTD Job build result here:
https://fledge-iot.readthedocs.io/en/fogl-5408/fledge_plugins.html
https://fledge-iot.readthedocs.io/en/fogl-5408/plugin_index.html
=> FOGL-5408 wip,poc,internal topic exclusion in plugin documentation

C/common/include/string_utils.h, C/common/string_utils.cpp, tests/unit/C/common/test_string_utils.cpp
please take a look at the IsRegex implementation in https://github.com/fledge-iot/fledge/pull/384
=> FOGL-5383:  OMFHint wildcarding

tests/unit/C/common/CMakeLists.txt, tests/unit/C/common/test_string_utils.cpp
=> FOGL-5452: fix unit tests on Centos 7

tests/system/python/packages/data/package_list.json
=> FOGL-5382 mqtt-readings south added in package tests

python/fledge/services/core/api/auth.py, python/fledge/services/core/routes.py, python/fledge/services/core/user_model.py, tests/system/python/api/test_authentication.py, tests/unit/python/fledge/services/core/api/test_auth_mandatory.py, tests/unit/python/fledge/services/core/api/test_auth_optional.py, tests/unit/python/fledge/services/core/test_user_model.py
Package based system tests are passing with the change
=> FOGL-5483 - User API fixes

docs/building_fledge/06_testing.rst
=> In Testing fledge documentation - incorrect path for coap & fogbench related fixes

docs/91_version_history.rst, docs/scripts/plugin_documentation
1. Removed foglamp plugins version history
2. Lint fixes
3. Changed DOCBRANCH to 1.9.1RC
=> Documentation fixes and changed DOCBRANCH

C/services/north/north.cpp
=> FOGL-5485 Reload persisted data on plugin restart

C/services/north/north.cpp
=> FOGL-5485 - 1.9.1RC

docs/91_version_history.rst
=> Fixed typos

python/fledge/services/core/api/north.py
=> FOGL-5493 duplicate entry & lint fixes in north API

python/fledge/services/core/api/north.py
=> 1.9.1RC FOGL-5493

docs/91_version_history.rst
=> Updated release notes

C/common/include/management_client.h, C/common/management_client.cpp, C/services/common/include/service_handler.h, C/services/common/service_security.cpp, C/services/south/include/south_api.h, C/services/south/include/south_service.h, C/services/south/south.cpp, C/services/south/south_api.cpp
FOGL-5144: initial implementation of authentication middleware
=> FOGL-5144: initial implementation of authentication middleware

docs/91_version_history.rst
=> Organized the version history

docs/scripts/plugin_documentation
=> Updated the DOCBRANCH value to develop

C/services/south/include/south_service.h, C/services/south/south.cpp, C/services/south/south_plugin.cpp
=> FOGL-5487 Add data persistance to south plugins

tests/system/python/packages/test_omf_north_service.py
=> Remove unwanted sleeps from test_omf_north_service.py

tests/system/python/packages/test_eds.py, tests/system/python/packages/test_lab.py
=> FOGL-5592: Added Naming Scheme in North configuration system tests

docs/plugin_developers_guide/03_01_DHT11.rst
=> FOGL-4156 Fix path

docs/processing_data.rst
=> FOGL-5625 Add section on why use filters

C/plugins/north/OMF/include/OMFHint.h, C/plugins/north/OMF/include/omf.h, C/plugins/north/OMF/omf.cpp, C/plugins/north/OMF/omfhints.cpp, C/plugins/north/OMF/plugin.cpp, C/tasks/north/sending_process/sending_process.cpp, tests/unit/C/plugins/common/test_omf_translation.cpp
```
---- asset_reading_catalogue  -------------------------------
1|1|Rotary
2|1|Rotary_2
3|1|Rotary_4
---- readings_1_1 -------------------------------
5|{"sinusoid":0.104528463,"OMFHint":"{\"AFLocation\":\"/Sites/Orange/Suez/ADN C1\"}"}|2021-06-29 13:16:30.913479+00:00|2021-06-29 13:16:32.571+00:00
6|{"sinusoid":0.207911691,"OMFHint":"{\"AFLocation\":\"/Sites/Orange/Suez/ADN C1\"}"}|2021-06-29 13:16:31.913830+00:00|2021-06-29 13:16:32.571+00:00
7|{"sinusoid":0.309016994,"OMFHint":"{\"AFLocation\":\"/Sites/Orange/Suez/ADN C1\"}"}|2021-06-29 13:16:32.913430+00:00|2021-06-29 13:16:33.916+00:00
8|{"sinusoid":0.406736643,"OMFHint":"{\"AFLocation\":\"/Sites/Orange/Suez/ADN C1\"}"}|2021-06-29 13:16:33.913799+00:00|2021-06-29 13:16:33.916+00:00
---- …
```
=> FOGL-5574: Enhance the OMF North plugin to accept hierarchy hints

docs/building_fledge/01_introduction.rst
=> FOGL-4880 unused link reference removed from documentation

docs/scripts/fledge_plugin_list
Custom RTD link is available here - https://fledge-iot.readthedocs.io/en/fogl-5462
=> FOGL-5462 None description fixes for plugin & other code refactoring fixes

docs/OMF.rst, docs/fledge-north-OMF.rst, docs/scripts/plugin_documentation
=> FOGL-5624 OMF documentation updates

C/common/include/string_utils.h, C/common/string_utils.cpp, C/plugins/north/OMF/include/omf.h, C/plugins/north/OMF/omf.cpp, C/plugins/north/OMF/plugin.cpp
```
{
"value" :
{
"names" :
{
"asset_1"   : "Position1/${room:unknown1}",
"asset_12"  : "Position1/${room:unknown1}",
"asset_2"   : "Position2/${room:unknown2}",
"asset_3"   : "Position3/${room:unknown3}",
"asset_31"  : "/Position31/${room:unknown3}",
"asset_4"   : "Position4",
"asset_5"   : "/Position5"
}
}
}
[
{ "name"          : "asset_1",
"sensor_values" : [
{ "name": "lux", "type": "number", "min": 0, "max": 10, "precision":0 },
{ "name": "room", "type": "enum", "list": [ "suit_1" ] },
{ "name": "l1",   "type": "enum", "list": [ "Sites_New" ] }
] },
{ "name"          : "asset_12",
"sensor_values" : [
{ "name": "lux", "type": "number", "min": 0, "max": 10, "precision":0 },
{ "name": "room", "type": "enum", "list": [ "suit_12" ] }
] },
{ …
```
=> FOGL-5575 : Update OMF metadata rules and AF Location

C/common/include/where.h, C/common/where.cpp, C/plugins/storage/postgres/connection.cpp, C/tasks/purge_system/CMakeLists.txt, C/tasks/purge_system/include/purge_system.h, C/tasks/purge_system/main.cpp, C/tasks/purge_system/purge_system.cpp, CMakeLists.txt, Makefile, VERSION, scripts/plugins/storage/postgres/downgrade/42.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/43.sql, scripts/plugins/storage/sqlite/downgrade/42.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/43.sql, scripts/plugins/storage/sqlitelb/downgrade/42.sql, scripts/plugins/storage/sqlitelb/init.sql, scripts/plugins/storage/sqlitelb/upgrade/43.sql, scripts/tasks/purge_system
Service Name: purge_system
Tables
- fledge.statistics_history
- fledge.tasks 
- fledge.log 
SQLite
```
year|day|key|value
2020|2020-04-01|KEY_03|3
2021|2021-05-01|KEY_01|3
2021|2021-06-01|KEY_02|10
2021|2021-06-02|KEY_01|5
```
Postgress
```
year |          day           |  key   | value 
------+------------------------+--------+-------
2020 | 2020-04-01 00:00:00+00 | KEY_03 |     3
2021 | 2021-05-01 00:00:00+00 | KEY_01 |     3
2021 | 2021-06-01 00:00:00+00 | KEY_02 |    10
2021 | 2021-06-02 00:00:00+00 | KEY_01 |     5
(4 rows)
```
Test case
```
--- statistics_history
INSERT INTO statistics_history (id, key, history_ts, value, ts) VALUES (2000, 'KEY_01', '2021-06-10 14:49:34.392', 1, '2021-06-14 14:49:34.392');
INSERT INTO statistics_history (id, key, history_ts, value, ts) VALUES (2001, …
```
=> Fogl 5468:  new C++ purge process to handle STATISTICS_HISTORY, AUDIT TRAILS and TASKS tables

VERSION
=> revert to 1.9.1

tests/system/python/packages/test_gcp_gateway.py
Custom Packages available at http://archives.fledge-iot.org/fixes/FOGL-5754
North GCP plugin: https://github.com/fledge-iot/fledge-north-gcp/pull/21
Also ran package system tests with given change - http://jenkins.dianomic.com:8080/view/Fledge%20Custom%20Jobs/job/fledge_packages_gcp_system_test/164/ - And it passes
=> FOGL-5754 PEM certs dir fixes in GCP package system tests & other PEP8 coding style violation fixes

scripts/fledge
=> fix mqtt-scripted on RHEL platform

C/services/common/north_python_plugin_handle.cpp
=> FOGL-5699 Fix plugin type

Makefile
Custom Packages are available at http://archives.fledge-iot.org/fixes/FOGL-5759
**Package content**
```
-rwxr-xr-x ubuntu/ubuntu     312 2021-07-30 16:21 ./usr/local/fledge/scripts/tasks/purge_system
```
=> FOGL-5759 purge_system script copied to scripts/tasks directory during script install target

docs/quick_start/index.rst, docs/quick_start/installing.rst, docs/quick_start/uninstalling.rst
=> FOGL-5774 quickstart guide fixes for installing fledge and also uninstall index added

docs/plugin_developers_guide/10_testing.rst
=> FOGL-5785 fix CMAKE_BUILD_TYPE documentation

C/services/common/include/binary_plugin_handle.h
test script
```
import json
import sys
import numpy
import pandas
def convert(message, topic):
s = pandas.Series([1, 3, 5, numpy.nan, 6, 8])
k = s[0]
asset = "asset_" + str(int(k))
return asset,  {"temperature_ok": 200.3}
```
=> FOGL-5793  : fix import pandas in foglamp-south-mqtt-scripted python script

python/fledge/services/core/api/repos/configure.py
```
$ sudo yum list available | grep fledge
```
**Example**
```
$ curl -sX POST http://localhost:8081/fledge/repository -d '{"url":"http://archives.fledge-iot.org", "version":"nightly"}'
{"message": "Package repository configured successfully.", "output_log": "/usr/local/fledge/data/configure_repo_output.txt"}
```
**CentOS**
Custom Package available at http://archives.fledge-iot.org/fixes/FOGL-4176/centos7/x86_64/
```
$ sudo cat /usr/local/fledge/data/configure_repo_output.txt
[fledge]
name=fledge Repository
baseurl=http://archives.fledge-iot.org/nightly/centos7/x86_64
enabled=1
gpgkey=http://archives.fledge-iot.org/RPM-GPG-KEY-fledge
gpgcheck=1
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Loading mirror speeds from …
```
=> FOGL-4176 RPM support added in configure repository REST API endpoint

C/common/include/config_category.h, C/common/include/management_client.h, C/tasks/purge_system/include/purge_system.h, C/tasks/purge_system/main.cpp, C/tasks/purge_system/purge_system.cpp
=> purge_system as a child category of Utilities category

docs/control.rst
=> FOGL-5828 Add data substitution method

C/services/common-plugin-interfaces/python/include/python_plugin_common_interface.h
=> fix Shutting down crash

docs/quick_start/installing.rst
=> FOGL-5794 epel release package documentation step added for Red Hat Linux

python/fledge/services/core/support.py
Content of support tar bundle be look like 
```
$ tar -xvf support-210831-11-06-57.tar.gz 
syslog-210831-11-06-57
syslogStorage-210831-11-06-57
syslog-MQTT-210831-11-06-57
syslog-RW-210831-11-06-57
syslog-Sys-210831-11-06-57
syslog-HT-210831-11-06-57
configuration-210831-11-06-57
audit-210831-11-06-57
schedules-210831-11-06-57
scheduled_processes-210831-11-06-57
statistics-history-210831-11-06-57
plugin-data-210831-11-06-57
streams-210831-11-06-57
service_registry-210831-11-06-57
machine-210831-11-06-57
psinfo-210831-11-06-57
scripts/
scripts/rw_py_script_readings35.py
package_logs/
software-210831-11-06-57
```
Software content be like 
```
$ cat software-210831-11-06-57
{
"plugins": [
{
"name": "pi_server",
"type": "north", …
```
=> FOGL-5874 software list added to support bundle tar

C/plugins/storage/sqlite/common/include/purge_configuration.h, C/plugins/storage/sqlite/common/purge_configuration.cpp, C/plugins/storage/sqlite/common/readings_catalogue.cpp, C/plugins/storage/sqlite/plugin.cpp, C/services/storage/include/plugin_configuration.h, C/services/storage/pluginconfiguration.cpp, C/services/storage/storage.cpp
=> FOGL-5809 Add exclusion list for purge

python/fledge/plugins/storage/common/backup.py, python/fledge/services/core/api/backup_restore.py, tests/unit/python/fledge/services/core/api/test_backup_restore.py
**Curl Examples**
```
$ curl -sX GET http://localhost:8081/fledge/backup | jq
{
"backups": [
{
"id": 3,
"date": "2021-09-06 12:47:22.392",
"status": "COMPLETED"
},
{
"id": 2,
"date": "2021-09-06 12:38:46.688",
"status": "COMPLETED"
},
{
"id": 1,
"date": "2021-09-06 11:33:44.143",
"status": "RESTORED"
}
]
}
$ curl -sX GET http://localhost:8081/fledge/backup?limit=2 | jq
{
"backups": [
{
"id": 3,
"date": "2021-09-06 12:47:22.392",
"status": "COMPLETED"
},
{
"id": 2,
"date": "2021-09-06 12:38:46.688",
"status": "COMPLETED"
}
]
}
$ curl -sX GET "http://localhost:8081/fledge/backup?limit=2&status=restored" | jq
{
"backups": [
{
"id": 1,
"date": "2021-09-06 11:33:44.143",
"status": "RESTORED"
}
]
}
$ curl -sX GET "http://localhost:8081/fledge/backup?limit=2&skip=1" | jq
{
"backups": [
{
"id": …
```
=> FOGL-5893 GET ALL Backups API fixes as per Limit, skip/offset given

C/services/north/data_send.cpp
FOGL-5920: North services repeat data
=> FOGL-5920: North services repeat data

C/services/south/south.cpp
=> Add retry of start method for poll as well as async plugins

C/services/north/data_send.cpp, C/services/north/include/data_load.h
FOGL-5934: fetch next readings block in case of all filtered out readings
=> FOGL-5934: fetch next readings block in case of all filtered out readings

C/plugins/north/OMF/omf.cpp, C/tasks/north/sending_process/sending_process.cpp, VERSION
=> FOGL-5929 - OMF: handle properly rows having only unsupported data - ignoring them

python/fledge/services/core/api/backup_restore.py
=> FOGL-5913 upload backup with multipart reader to allow max size

C/services/north/north.cpp
FOGL-5488: remove lock acquire in shutdown routine
=> FOGL-5488: remove lock acquire in shutdown routine

python/fledge/plugins/storage/common/lib.py, python/fledge/plugins/storage/postgres/backup_restore/lib.py, python/fledge/plugins/storage/postgres/backup_restore/restore_postgres.py, python/fledge/plugins/storage/sqlite/backup_restore/restore_sqlite.py
Fixed for both Sqlite & PostgreSQL engine
Custom Packages are available at - http://archives.fledge-iot.org/fixes/FOGL-5921
=> FOGL-5921 Old backup entries are restored when we restore a backup

docs/plugin_developers_guide/04_north_plugins.rst
=> FOGL-5925 north plugin documentation to plugin developer guide

tests/system/lab/reset, tests/system/lab/test.config
=> FOGL-5965: Added support for sqlitelb in lab script

C/services/south/include/ingest.h, C/services/south/ingest.cpp
=> FOGL-5830 Tentative fix - take out queue mutex before looking at first

C/services/north/data_send.cpp
FOGL-5973: fix for retry parameter in North service
tested with
sleepTime = 1
MaximumRetry = 3
httpTimeout = 10
Setup:
South service with sinusoid plugin
North service with httpc plugin configured to send data to another Fledge instance
Step 1: change the IP address in URL address to something behind firewall or not existent in the LAN
Step 2: after a bit change back the IP address to good one:
reconfiguration will happen after retries and timeout and readings data are going to north destination
=> FOGL-5973: fix for retry parameter in North service

docs/91_version_history.rst
=> Version History

scripts/common/json_parse.py, scripts/extras/update_task.apt
> RPM support - This may be with separate JIRA as it requires changes in centralised package repository as well.
FOGL-5975 created
Tested with both Sqlite & Postgres engines.
Custom Packages are available at http://archives.fledge-iot.org/fixes/FOGL-5899
=> FOGL-5899 Update APT package via API

C/plugins/storage/sqlite/common/connection.cpp, C/plugins/storage/sqlite/common/include/connection.h, C/plugins/storage/sqlite/common/readings.cpp, tests/unit/C/services/storage/sqlite/expected_ETC_UTC/117, tests/unit/C/services/storage/sqlite/expected_EUROPE_ROME/117
=> FOGL-5970 : multiReadinsg/Purge : purge by age deletes more data than wanted/needed

C/services/common/include/binary_plugin_handle.h, C/services/common/include/plugin_manager.h, C/services/common/plugin_manager.cpp, C/services/storage/storage.cpp
=> Cherry Pick fix for FOGL-5977

python/fledge/plugins/north/ocs/ocs.py, python/fledge/services/core/api/plugins/common.py
Custom Package is available at http://archives.fledge-iot.org/fixes/FOGL-5949 and same will be available for white-labelled
**Testing notes**
All System tests are good. 
ub18 - `Fledge%20Nightly%20Jobs/job/fledge_nightly_build_ub1804/877/`
Ub20 - `Fledge%20Nightly%20Jobs/job/fledge_nightly_build_ub2004/188/`
Failing tests are flaky ones (only 2)
centos - `Fledge%20Nightly%20Jobs/job/fledge_nightly_build_centos/656/`
- RpiZero - `Fledge%20Custom%20Jobs/job/fledge_packages_installation_rpi0/384/`
- Ub18 - `Fledge%20Custom%20Jobs/job/fledge_packages_installation_ub1804/453/`
White-labelled
- FL-ub20 - `WL%20Custom%20Jobs/job/fledge_wl_packages_installation_ub2004/81/` - Also it resolved the FOGL-2935 (which is the …
=> FOGL-5949 file descriptor issue fixes for plugin discovery

scripts/extras/update_task.apt, scripts/extras/update_task.yum
=> FOGL-6015 sqlitelb support added in package update API

Makefile
=> FOGL-6018 Add fledge_mnt to scripts install

python/fledge/services/core/api/update.py
=> FOGL-6016 exception handling added for update API

CONTRIBUTING.md
=> FOGL-5983 removal of unsupported xml/html tag in Contributing file

python/fledge/services/core/api/utils.py
**Testing notes:**
No regression has been found with the given change.
Existing unit/system tests are good. Also ran CI custom job against ub20 and CentOS platform to verify with fresh environments.
1) Fledge%20Nightly%20Jobs/job/fledge_nightly_build_ub2004/229/
2) Fledge%20Nightly%20Jobs/job/fledge_nightly_build_centos/697/
=> FOGL-6078 case sensitive check added for C-type plugins in api util discovery

C/services/north-plugin-interfaces/python/python_plugin_interface.cpp
=>  compile error fix on bullseye Raspberry Pi OS

python/fledge/tasks/purge/purge.py, tests/unit/python/fledge/tasks/purge/test_purge.py
=> FOGL-6087 error handling added at python side when purge data response is not coming from Storage API & other lint fixes

python/fledge/services/core/support.py
Custom Packages available at http://archives.fledge-iot.org/fixes/FOGL-6082
**Testing Notes:**
Package test
```
$ cat support-211207-10-22-52/machine-211207-10-22-52 
{
"about": "Machine resources",
"platform": "linux",
"totalMemory": "978Mi",
"usedMemory": "206Mi",
"freeMemory": "178Mi",
"totalDiskSpace_MB": 7876,
"usedDiskSpace_MB": 2297,
"freeDiskSpace_MB": 5562,
"hostnameInfo": {
"Statichostname": "ip-10-0-0-35",
"Iconname": "computer-vm",
"Chassis": "vm",
"MachineID": "d4db90bdf6ce4cf28241648a9465845b",
"BootID": "cc327097adc040019442fa825de5ba9d",
"Virtualization": "xen",
"OperatingSystem": "Ubuntu20.04.3LTS",
"Kernel": "Linux5.4.0-1038-aws",
"Architecture": "x86-64"
},
"cpuArchitectureInfo": {
"Architecture": "x86_64", …
```
=> FOGL-6082 hostname and cpu architecture info added in machine support bundle

scripts/plugins/storage/sqlitelb/downgrade/44.sql, scripts/plugins/storage/sqlitelb/init.sql, scripts/plugins/storage/sqlitelb/upgrade/45.sql
=> FOGL-6064 control service schema addition for sqlitelb

scripts/plugins/storage/postgres/downgrade/44.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/45.sql
=> FOGL-6064 control service schema addition for PostgreSQL

VERSION, python/fledge/services/core/api/control_service/acl_management.py, python/fledge/services/core/api/control_service/exceptions.py, python/fledge/services/core/api/control_service/script_management.py, python/fledge/services/core/routes.py, scripts/plugins/storage/postgres/downgrade/44.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/45.sql, scripts/plugins/storage/sqlite/downgrade/44.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/45.sql, scripts/plugins/storage/sqlitelb/downgrade/44.sql, scripts/plugins/storage/sqlitelb/init.sql, scripts/plugins/storage/sqlitelb/upgrade/45.sql
=> FOGL-6064 control script and acl schema addition

Makefile, VERSION, python/fledge/services/core/server.py, scripts/plugins/storage/postgres/downgrade/45.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/46.sql, scripts/plugins/storage/sqlite/downgrade/45.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/46.sql, scripts/plugins/storage/sqlitelb/downgrade/45.sql, scripts/plugins/storage/sqlitelb/init.sql, scripts/plugins/storage/sqlitelb/upgrade/46.sql, tests/system/python/api/test_audit.py
Custom Packages are available at http://archives.fledge-iot.org/fixes/FOGL-6130/
Health of unit and system tests are good with the change. Here are the test result against ub1804 - `{JENKINS_BASE_URI}/Fledge%20Nightly%20Jobs/job/fledge_nightly_build_ub1804/972/testReport/`
=> FOGL-6130 - Auto start of control dispatcher and other related fixes

C/common/asset_tracking.cpp, C/common/include/asset_tracking.h, C/common/include/management_client.h, C/common/management_client.cpp, C/services/common/include/plugin_api.h, C/services/north/include/north_service.h, C/services/north/north.cpp
Supporting checkout for fledge-service-dispatcher
=> FOGL-6066 Support for fledge-service-dispatcher

C/common/asset_tracking.cpp, C/common/include/asset_tracking.h, C/common/include/management_client.h, C/common/management_client.cpp
FOGL-6146: getService of AssetTracker implemented
Example method call:
AssetTracker::getAssetTracker()->getService("Ingest", "asset_1");
=> FOGL-6146: getService of AssetTracker implemented

python/fledge/services/core/api/control_service/acl_management.py, python/fledge/services/core/api/control_service/script_management.py
Before test this you need to make sure that data reset is required for control tables. After that you will get desired result.
=> Fogl 6152 - steps of the control script updated

C/plugins/storage/sqlitememory/plugin.cpp
FOGL-6172: fix readings purge in sqlitememory plugin
=> FOGL-6172: fix readings purge in sqlitememory plugin

tests/unit/python/fledge/services/south/test_services_south_server.py
=> FOGL-6161: test_services_south_server.py unit test marked obsolete

requirements.sh
FOGL-6187: pass -f parameter in cmake3 link creation
=> FOGL-6187: pass -f parameter in cmake3 link creation

tests/unit/python/fledge/services/core/api/test_backup_restore.py
=> Fixed the backup test, failing on Rpi Bullseye

C/services/common/plugin_manager.cpp
=> FOGL-6202 Improve diagnostic and fix code layout

docs/control.rst
=> FOGL-6205 Fix image name

docs/quick_start/installing.rst
=> FOGL-6216 Fixed typo

python/fledge/services/core/api/control_service/acl_management.py, python/fledge/services/core/api/control_service/script_management.py
=> FOGL-6230 control script API fixes, removal of str/eval & allow update script name

C/services/common/include/service_handler.h, C/services/north/include/data_load.h, C/services/north/include/north_service.h, C/services/south/include/ingest.h, C/services/south/include/south_service.h, C/services/storage/include/storage_service.h
FOGL-5144: addition of isRunning() routine
=> FOGL-5144: addition of isRunning() routine

python/fledge/services/core/server.py, tests/unit/python/fledge/services/core/test_server.py
… token at startup was assigned
=> FOGL-5144 patch: fix the security flaw that allowed registration without token 

python/fledge/services/core/api/control_service/acl_management.py
FOGL-6244: check and set empty value for security category
=> FOGL-6244: check and set empty value for security category

scripts/tasks/check_certs
FOGL-6233: fix for certificates automatic renewal
=> FOGL-6233: fix for certificates automatic renewal

docs/plugin_developers_guide/10_testing.rst
=> Fix valgrind name

VERSION, python/fledge/services/core/api/control_service/script_management.py, python/fledge/services/core/routes.py, python/fledge/tasks/automation_script/__main__.py, scripts/plugins/storage/postgres/downgrade/46.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/47.sql, scripts/plugins/storage/sqlite/downgrade/46.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/47.sql, scripts/plugins/storage/sqlitelb/downgrade/46.sql, scripts/plugins/storage/sqlitelb/init.sql, scripts/plugins/storage/sqlitelb/upgrade/47.sql, scripts/tasks/automation_script
**Note**
I have tested with modbus-C plugin having control map configured with help of diagslave simulator on linux
*) dispatcher write API with both destination types (service and script)
*) also tested substitution at run time 
Able to test write humidity with value configured in script and successfully write that value in modbus-device simulation
=> FOGL-6215 scheduled task that can run an automation script

python/fledge/services/core/api/control_service/script_management.py
ACL API will fix until FOGL-6258 is resolved
=> FOGL-6246 API validation added in control script

docs/plugin_developers_guide/11_WSL2.rst, docs/plugin_developers_guide/index.rst
Added new article on Windows Subsystem for Linux (WSL2)
=> Fogl 6262.a

python/fledge/services/core/api/control_service/script_management.py
=> FOGL-6286 ACL field optional on UPDATE script

docs/control.rst, docs/rest_api_guide/02_RESTadmin.rst, tests/system/python/iprpc/test_iprpc.py
=> Project text occurrence fixes

C/services/north/data_load.cpp, C/services/north/include/data_load.h, C/services/north/north.cpp
Addition of blockSize to North service
=> FOGL-6280: Addition of blockSize to North service

Makefile
=> FOGL-6301 automation missing script added in make install target

C/plugins/storage/postgres/connection.cpp, C/plugins/storage/sqlite/common/readings.cpp, C/plugins/storage/sqlitelb/common/readings.cpp
FOGL-6111: Return empty result set with not purged data
=> FOGL-6111: Return empty result set with not purged data

docs/control.rst
=> Update control configuration documentation

python/fledge/services/core/api/control_service/script_management.py, tests/unit/python/fledge/services/core/api/control_service/test_script_management.py
=> FOGL-6328 dispatcher category name fixes in schedule task automation script as per FOGL-6311 changes

tests/system/python/api/test_plugin_discovery.py, tests/system/python/packages/test_available_and_install_api.py
NOTE: All system tests are passing with the change. Check JIRA detailed comments over there.
=> FOGL-6336 UPDATE API & Package based system tests fixes as per FOGL-5665; as two default north based plugins are removed

python/fledge/services/core/api/browser.py, tests/unit/python/fledge/services/core/api/test_browser_assets.py
=> FOGL-6312 exclude/include request query param added in browser asset and readings API endpoint

C/services/common-plugin-interfaces/python/include/python_plugin_common_interface.h, C/services/north/north_plugin.cpp
=> FOGL-6345: Initialize options in plugin info if not specified in plugin code

python/fledge/services/core/api/control_service/script_management.py, tests/unit/python/fledge/services/core/api/control_service/test_script_management.py
=> FOGL-6285 parameter support added in schedule configuration task REST API endpoint

C/services/filter-plugin-interfaces/python/python_plugin_interface.cpp, C/services/north-plugin-interfaces/python/python_plugin_interface.cpp, C/services/south-plugin-interfaces/python/python_plugin_interface.cpp
FOGL-6358: fix memory leak in python north plugin send
=> FOGL-6358: fix memory leak in python north plugin send

C/common/form_data.cpp, C/common/include/form_data.h, C/thirdparty/Simple-Web-Server/server_http.hpp
FOGL-6310: form data upload class
=> FOGL-6350: form data upload class

python/fledge/services/core/api/control_service/script_management.py, tests/unit/python/fledge/services/core/api/control_service/test_script_management.py
=> FOGL-6356 Delete category with parent-child relation And related schedule deletion handling added in delete script Admin API endpoint

python/fledge/services/core/api/control_service/script_management.py, python/fledge/tasks/automation_script/__main__.py, tests/unit/python/fledge/services/core/api/control_service/test_script_management.py
=> FOGL-6363 -automation-script suffix added in schedule category for an automation script task

C/common/pythonreading.cpp
=> FOGL-5665: Memory leak fix

C/plugins/storage/postgres/CheckRhPg.cmake, docs/REDHAT.rst, docs/building_fledge/building_fledge.rst, docs/storage.rst, requirements.sh, scripts/fledge, tests/system/python/scripts/install_c_plugin, tests/system/python/scripts/install_c_service, tests/unit/C/cmake_pg/CheckRhPg.cmake, tests/unit/C/plugins/storage/postgres/CheckRhPg.cmake
=> Upgrade of postgres to version 13

tests/system/python/conftest.py
=> Delete the whole AF hierarchy after completion of system test

C/thirdparty/rapidjson/docker/debian/Dockerfile
=> Remove unused code causing CVE alerts

docs/plugin_developers_guide/035_CPP.rst
=> FOGL-6388 literal block highlight, malformed table and some typos fixes in C++ support classes doc

C/plugins/storage/sqlite/common/include/readings_catalogue.h, C/plugins/storage/sqlite/common/readings.cpp, C/plugins/storage/sqlite/common/readings_catalogue.cpp
FOGL-6332: addition of transaction boundaries in 'sqlite' multidb plugin
=> FOGL-6332: addition of transaction boundaries

C/plugins/storage/sqlite/common/readings_catalogue.cpp
Fixed define usage in log messages
=> Fixed define usage in log messages

docs/plugin_developers_guide/09_packaging.rst
=> iec common additional package updated in documentation

C/plugins/north/OMF/omf.cpp
Signed-off-by: Ray Verhoeff <ray@dianomic.com>
=> Bypass processing of unsupported OMF data types

tests/system/plugins/south/fledge-south-testcard/plugin.cpp
Hi @MarkRiddoch, 
I have changed the test card plugin a lit bit for making height and width of image configurable. 
This is the resultant image of 256X256 24 bit depth from the plugin.
=> FOGL-6408. Added image height and image width parameters inside configuration of test card plugin. 

C/common/include/join.h, C/common/include/query.h, C/common/join.cpp, C/common/query.cpp, C/plugins/storage/sqlite/common/connection.cpp, C/plugins/storage/sqlite/common/include/connection.h
=> FOGL-6310 Initial implementation of join functionality for SQLite only

tests/system/python/packages/test_pi_webapi.py
=> FOGL-6321: Check reconfig of north tasks

docs/plugin_developers_guide/09_packaging.rst
=> FOGL-5798 plugin developer guide updated for newly s2opcua additional package

C/common/include/management_client.h, C/common/management_client.cpp
FOGL-6480: token cache fix
Store token object instead of the string value
=> FOGL-6480: token cache fix

scripts/plugins/storage/sqlite/downgrade/48.sql, scripts/plugins/storage/sqlite/upgrade/49.sql
=> FOGL-6520 fix upgrade script

C/plugins/storage/sqlite/common/connection.cpp
=> FOGL-6531 Add prefix to AND and OR conditions

scripts/plugins/storage/sqlitelb/downgrade/48.sql, scripts/plugins/storage/sqlitelb/upgrade/49.sql
=> FOGL-6520 sql fixes for sqlitelb engine

C/services/north-plugin-interfaces/python/python_plugin_interface.cpp
=> FOGL-6512 Correct level of debug messages

python/fledge/services/core/api/notification.py, tests/unit/python/fledge/services/core/api/test_notification.py
FOGL-6495: POST API fix for new delivery channel
=> FOGL-6495: POST API fix for new delivery channel

python/fledge/services/core/proxy.py, python/fledge/services/core/server.py, python/requirements.txt
Also ran custom job with the given change and all system tests are passing. As such no regression found.
=> FOGL-6530 Proxy API mutlipart form support and other cleanup fixes

scripts/plugins/storage/sqlite.sh, scripts/plugins/storage/sqlitelb.sh
=> FOGL-6564 cleanup service schema on reset

C/common/form_data.cpp
=> FOGL-6563 Fix issue with running into next section of payload when

scripts/plugins/storage/postgres/downgrade/49.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/50.sql, scripts/plugins/storage/sqlitelb/downgrade/49.sql, scripts/plugins/storage/sqlitelb/init.sql, scripts/plugins/storage/sqlitelb/upgrade/50.sql
FOGL-6524: addition of schema upgrade for postgres and sqlitelb
=> FOGL-6524: addition of schema upgrade for postgres and sqlitelb

C/common/include/process.h, C/common/process.cpp, C/services/north/include/north_service.h, C/services/north/north.cpp, C/services/south/include/south_service.h, C/services/south/south.cpp, C/tasks/north/sending_process/include/sending.h, C/tasks/north/sending_process/sending.cpp, C/tasks/north/sending_process/sending_process.cpp, C/tasks/purge_system/purge_system.cpp, C/tasks/statistics_history/stats_history.cpp
configuration etc without a full service execution
=> FOGL-5181 Add --dryrun flag to services and tasks to allow population of

C/services/common/service_security.cpp, python/fledge/services/core/api/control_service/acl_management.py, tests/unit/python/fledge/services/core/api/control_service/test_acl_management.py
FOGL-6594: Security category changes
All services create security category with AuthenticatedCaller boolean switch
=> FOGL-6594: Security category changes

VERSION, scripts/plugins/storage/postgres/downgrade/50.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/51.sql, scripts/plugins/storage/sqlite/downgrade/50.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/51.sql, scripts/plugins/storage/sqlitelb/downgrade/50.sql, scripts/plugins/storage/sqlitelb/init.sql, scripts/plugins/storage/sqlitelb/upgrade/51.sql
=> FOGL-6561 Add new audit codes for external services

scripts/plugins/storage/postgres/init.sql
=> FOGL-6609 Add missing comma

python/fledge/services/core/api/support.py
=> FOGL-6608 Limit and Offset supported with nontotals true in syslog API

docs/OMF.rst
=> OMF broken link fixes in documentation

C/plugins/storage/postgres/connection.cpp, C/plugins/storage/postgres/include/connection.h, C/plugins/storage/postgres/plugin.cpp, C/plugins/storage/sqlite/common/include/connection.h, C/plugins/storage/sqlite/common/include/readings_catalogue.h, C/plugins/storage/sqlite/common/readings.cpp, C/plugins/storage/sqlite/plugin.cpp, C/plugins/storage/sqlitelb/common/include/connection.h, C/plugins/storage/sqlitelb/common/readings.cpp, C/plugins/storage/sqlitelb/plugin.cpp, C/plugins/storage/sqlitememory/include/connection.h, C/plugins/storage/sqlitememory/plugin.cpp
FOGL-6664: purge by asset for sqlitelb plugin
=> FOGL-6664: purge by asset for storage plugins

docs/building_pipelines.rst
=> FOGL-6655 malformed hyperlink target fixes in pipelines doc

C/common/include/storage_client.h, C/common/storage_client.cpp, C/plugins/storage/postgres/connection.cpp, C/plugins/storage/postgres/include/connection.h, C/plugins/storage/postgres/plugin.cpp, C/plugins/storage/sqlite/common/include/connection.h, C/plugins/storage/sqlite/common/include/readings_catalogue.h, C/plugins/storage/sqlite/common/readings.cpp, C/plugins/storage/sqlite/plugin.cpp, C/plugins/storage/sqlitelb/common/include/connection.h, C/plugins/storage/sqlitelb/common/readings.cpp, C/plugins/storage/sqlitelb/plugin.cpp, C/plugins/storage/sqlitememory/include/connection.h, C/plugins/storage/sqlitememory/plugin.cpp, C/services/storage/include/storage_plugin.h, C/services/storage/storage_api.cpp, C/services/storage/storage_plugin.cpp, python/fledge/common/storage_client/exceptions.py, python/fledge/common/storage_client/storage_client.py, python/fledge/services/core/api/browser.py, tests/unit/python/fledge/common/storage_client/test_sc_exceptions.py, tests/unit/python/fledge/common/storage_client/test_storage_client.py, tests/unit/python/fledge/services/core/api/test_browser_assets.py
=> FOGL-6666 Addition of API and storage service support for purge by asset

C/plugins/storage/postgres/plugin.cpp, C/plugins/storage/sqlite/plugin.cpp, C/plugins/storage/sqlitelb/plugin.cpp, C/plugins/storage/sqlitememory/plugin.cpp
FOGL-6664: storage plugin interface version bumped
=> FOGL-6664: storage plugin interface version bumped

tests/unit/C/common/CMakeLists.txt
The unit tests on coral board are now passing.
=> FOGL-6676 Fix for unit test failure on coral board.

C/plugins/storage/sqlitememory/plugin.cpp
=> FOGL-6700 Fix sqlitememory plugin such that it has a configuration

C/services/common/service_security.cpp
FOGL-6737: refresh token error forces service shutdown
=> FOGL-6737: refresh token error forces service shutdown

C/common/include/where.h, C/common/where.cpp, C/plugins/storage/sqlite/common/connection.cpp, python/fledge/common/storage_client/payload_builder.py, tests/unit/C/common/test_query.cpp, tests/unit/python/fledge/common/storage_client/data/payload_and_where_isnull.json, tests/unit/python/fledge/common/storage_client/data/payload_and_where_notnull.json, tests/unit/python/fledge/common/storage_client/data/payload_multiple_and_where.json, tests/unit/python/fledge/common/storage_client/data/payload_multiple_or_where.json, tests/unit/python/fledge/common/storage_client/data/payload_or_where_isnull.json, tests/unit/python/fledge/common/storage_client/data/payload_or_where_notnull.json, tests/unit/python/fledge/common/storage_client/data/payload_where_condition_isnull.json, tests/unit/python/fledge/common/storage_client/data/payload_where_condition_notnull.json, tests/unit/python/fledge/common/storage_client/test_payload_builder.py
=> FOGL-6740 Add support for IsNull and NotNull conditions

C/plugins/north/OMF/plugin.cpp, python/fledge/services/core/api/plugins/data.py
=> FOGL-6724 Fix import of persisted plugin data

python/fledge/common/acl_management.py, python/fledge/common/acl_manager.py, python/fledge/common/configuration_manager.py, python/fledge/common/microservice_management_client/microservice_management_client.py, python/fledge/services/core/api/control_service/acl_management.py
Notify service if acl is updated /deleted.
Steps
```
export FLEDGE_ROOT=/home/deepanshu/foglamp_workspace/FOGL-6612/fledge
$FLEDGE_ROOT/scripts/fledge kill 
echo YES | $FLEDGE_ROOT/scripts/fledge reset
$FLEDGE_ROOT/scripts/fledge start
curl -sX POST http://localhost:8081/fledge/service -d '{"name":"sine1","type":"south","plugin":"sinusoid","enabled":false,"config":{"assetName":{"value":"asset1"}}}' |jq
curl -sX POST http://localhost:8081/fledge/ACL -d '{"name":"acl1","service":[{"name":"Fledge Core"},{"type":"Core"}],"url":[{"url":"/fledge/category","acl":[{"type":"Core"}]}]}' | jq
curl -sX POST http://localhost:8081/fledge/ACL -d '{"name":"acl2","service":[{"name":"Fledge Core"},{"type":"Core"}],"url":[{"url":"/fledge/category","acl":[{"type":"Core"}]}]}' | jq
curl -sX PUT …
```
=> FOGL-6752: Notify service if acl is updated or deleted for /fledge/ACL endpoint. Also do it when it is Attached or detached to a service.

C/plugins/storage/postgres/connection.cpp, C/plugins/storage/sqlitelb/common/connection.cpp
FOGL-6742: isnull and not null added to sqlitelb and postgres
=> FOGL-6742: isnull and not null added to sqlitelb and postgres

C/common/asset_tracking.cpp, C/common/include/asset_tracking.h, C/common/include/expression.h, C/common/include/insert.h, C/common/include/management_client.h, C/common/include/resultset.h, C/common/management_client.cpp, C/plugins/storage/postgres/connection.cpp, C/plugins/storage/sqlite/common/connection.cpp, C/plugins/storage/sqlitelb/common/connection.cpp, C/services/south/include/ingest.h, C/services/south/ingest.cpp
FOGL-6721: initial implementation of un-deprecate assets
deprecated assets are un-deprecated only at service start.
Current change is for "sqlite" storage plugin
=> FOGL-6721: un-deprecate asset tracking records

C/common/include/plugin_data.h, C/common/plugin_data.cpp
=> FOGL-6772 Add state to know if we have loaded data from the database

C/common/include/plugin_data.h, C/common/plugin_data.cpp
=> FOGL-6772 cherry-picked

C/services/south/ingest.cpp, VERSION, python/fledge/services/core/api/asset_tracker.py, scripts/plugins/storage/postgres/downgrade/53.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/54.sql, scripts/plugins/storage/sqlite/downgrade/53.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/54.sql, scripts/plugins/storage/sqlitelb/downgrade/53.sql, scripts/plugins/storage/sqlitelb/init.sql, scripts/plugins/storage/sqlitelb/upgrade/54.sql
FOGL-6773: Add audit log for deprecated / un-depreacated assets
=> FOGL-6773: Add audit log for deprecated / un-depreacated assets

tests/system/python/api/test_audit.py
=> Audit system test fixes as per FOGL-6773 changes

python/fledge/plugins/common/utils.py, python/fledge/services/core/api/plugins/data.py
=> FOGL-6771 Plugin Data API extension improvements

README.rst
=> FOGL-6790 Update README

C/common/management_client.cpp, python/fledge/services/core/api/update.py, scripts/extras/update_task.apt, scripts/extras/update_task.yum, scripts/fledge
FOGL-6760: initial implementation
=> FOGL-6760: package management fixes for apt and yum

docs/plugin_developers_guide/09_packaging.rst
=> plugin packaging doc updated for C-based plugins

README.rst, python/fledge/common/acl_manager.py, python/fledge/services/core/api/control_service/acl_management.py, python/fledge/services/core/api/control_service/script_management.py, tests/unit/python/fledge/services/core/api/control_service/test_acl_management.py, tests/unit/python/fledge/services/core/api/control_service/test_script_management.py
1. Delete the record from acl_usage table when script or acl is deleted.
2. Update the acl in the acl_usage table when acl attached to script is updated. Do not do if acl contents are updated. As acl name is not changed.
3.  When an acl is attached to script update the acl usage table as well.
=> FOGL-6750. acl_usage table changes only for script. 

tests/system/memory_leak/config.sh, tests/system/memory_leak/test_memcheck.sh
I have updated the **test_memcheck.sh** file. 
The  **adding_sinusoid** is replaced by **add_sinusoid**
=> function call fixes in memory leak system test 

C/plugins/storage/sqlite/common/connection.cpp
=> FOGL-6889 Fix return in createSchema

tests/system/python/api/test_authentication.py
Fixed system tests for authentication..
=> Fixed system tests for authentication. FOGL-6894.

C/services/south/include/south_service.h, C/services/south/south.cpp
=> FOGL-6897 - Fix issue if reading rate unit is changed without changing

C/common/config_category.cpp, C/common/include/config_category.h, C/services/south/south.cpp
=> FOGL-6896 Enforce minimum value for reading rate

tests/system/python/packages/test_authentication.py
Signed-off-by: Praveen Garg <praveen.garg@nerdapplabs.com>
=> FOGL-6894 (patch) package system test fix - auth tests

python/fledge/common/microservice_management_client/microservice_management_client.py, python/fledge/services/core/api/auth.py, python/fledge/services/core/api/health.py, python/fledge/services/core/routes.py
Request Example 
`curl -sX GET http://localhost:8081/fledge/health/storage  |jq`
Sample Response 
```
{
"uptime": 11,
"name": "Fledge Storage",
"statistics": {
"commonInsert": 28,
"commonSimpleQuery": 2,
"commonQuery": 91,
"commonUpdate": 0,
"commonDelete": 1,
"readingAppend": 0,
"readingFetch": 0,
"readingQuery": 1,
"readingPurge": 0
},
"disk": {
"used": 94831296,
"usage": 82,
"available": 21374336,
"status": "green"
}
}
```
=> FOGL-6887 API to get Storage & data directory disk health

scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/sqlitelb/init.sql
=> Missing data column added in asset_tracker table for PostgreSQL & sqlitelb engine (init.sql)

C/services/north/north.cpp
=> FOGL-6935 Fix incorrect JSON for NorthService::operation

C/plugins/storage/sqlite/common/connection.cpp, C/plugins/storage/sqlite/common/connection_manager.cpp, C/plugins/storage/sqlite/common/include/connection.h, C/plugins/storage/sqlite/common/include/connection_manager.h, C/plugins/storage/sqlite/plugin.cpp, C/plugins/storage/sqlitelb/common/connection.cpp, C/plugins/storage/sqlitelb/common/connection_manager.cpp, C/plugins/storage/sqlitelb/common/include/connection.h, C/plugins/storage/sqlitelb/common/include/connection_manager.h, C/plugins/storage/sqlitelb/plugin.cpp, C/plugins/storage/sqlitememory/connection.cpp, C/plugins/storage/sqlitememory/include/connection.h, docs/storage.rst
=> FOGL-6925 Add periodic SQLite vacuum

C/plugins/utils/get_plugin_info.cpp
=> FOGL-6938 Fix crash with incorrect argument count for get_plugin_info

python/fledge/services/core/api/health.py, python/fledge/services/core/routes.py
Example 
```
$ curl -sX GET http://localhost:8081/fledge/health/logging | jq 
{
"levels": [
{
"name": "sss",
"level": "warning"
}
],
"disk": {
"used": 95711760,
"usage": 83,
"available": 20493872
}
}
```
=> Fogl 6877 API level changes for getting health of logging.

python/fledge/common/process.py, python/fledge/plugins/storage/postgres/backup_restore/backup_postgres.py, python/fledge/plugins/storage/postgres/backup_restore/restore_postgres.py, python/fledge/plugins/storage/sqlite/backup_restore/backup_sqlite.py, python/fledge/plugins/storage/sqlite/backup_restore/restore_sqlite.py, python/fledge/services/core/server.py, python/fledge/tasks/automation_script/__main__.py, python/fledge/tasks/north/sending_process.py, tests/system/python/api/test_audit.py, tests/system/python/api/test_configuration.py
=> FOGL-1904 For Python tasks configuration available at boot startup with dryrun mechanism

docs/rest_api_guide/03_RESTservices.rst, docs/rest_api_guide/06_GrafanaExamples.rst
=> malformed table & untitled short fixes in rest api developer guide doc

C/services/north/data_load.cpp, C/tasks/north/sending_process/sending_process.cpp
=> FOGL-6950 Add option to send audit log table north

docs/scripts/fledge_plugin_list, docs/scripts/plugin_and_service_documentation
=> FOGL-6978 exclusion list fixes in documentation scripts

C/common/include/reading_set.h, C/common/management_client.cpp, C/common/reading_set.cpp
=> FOGL-6959 Allow for recursion in JSON objects when converting to

C/plugins/common/ocs.cpp
=> Remove debug left in ADH

python/fledge/services/core/api/audit.py
**Curl Sample Ouput**
1. GET audit entries with source AUMRK
```
$ curl -sX GET http://localhost:8081/fledge/audit?source=AUMRK | jq
{
"audit": [
{
"details": {
"reason": "Audit log failure",
"version": "1.0.1"
},
"severity": "INFORMATION",
"source": "AUMRK",
"timestamp": "2022-10-10 15:41:08.592"
},
{
"details": {
"reason": "Audit log updates for deployment.",
"version": "1.0.0"
},
"severity": "INFORMATION",
"source": "AUMRK",
"timestamp": "2022-10-10 15:37:26.427"
}
],
"totalCount": 2
}
```
2. GET audit entries with source AUMRK & since (datetime string) - when match records are available
```
$ curl -sX GET "http://localhost:8081/fledge/audit?source=AUMRK&since=2022-10-10%2015:37:00" | jq
{
"audit": [
{
"details": {
"reason": "Audit log …
```
=> FOGL-7004 (PART-B) since request optional param support added in GET audit API

C/services/north/north.cpp
=> FOGL-7009: escape quotes in write values and operation parameters

docs/scripts/fledge_plugin_list, docs/scripts/plugin_and_service_documentation
With the given change. Below is the
Custom RTD Link: https://fledge-iot.readthedocs.io/en/fogl-6973/index.html
Broken link now fixed https://fledge-iot.readthedocs.io/en/fogl-6973/plugins/fledge-north-gcp_python/index.html
=> FOGL-6973 - private repos handling added in documentation scripts & other fixes

scripts/common/audittime.py, scripts/common/disk_usage.py, scripts/common/loglevel.py, scripts/common/service_status.py, scripts/fledge, tests/system/python/pair/test_c_north_service_pair.py
=> FOGL-7001 Add basic healthcheck option

C/services/south/south_api.cpp
=> FOGL-7039 improve control operation failure diagnostics

docs/91_version_history.rst
Signed-off-by: Praveen Garg <praveen.garg@nerdapplabs.com>
=> 2.0.1 change-logs cleanup

C/plugins/storage/postgres/plugin.cpp, C/services/north/north.cpp, C/services/south/south.cpp, C/services/storage/storage.cpp
=> FOGL-7058 Resolve warning on Ubuntu 18.04 platform

C/common/management_client.cpp
=> FOGL-7072: Error logs coming repeatedly when adding piserver south plugin

C/common/management_client.cpp, C/services/south/ingest.cpp
=> FOGL-7073: fixed code for unDeprecated StorageAssetTracking tuple

python/fledge/services/core/api/configuration.py
Signed-off-by: Praveen Garg <praveen.garg@nerdapplabs.com>
=> FOGL-7080 Fix check for management API vs User API for configuration changes

C/common/storage_asset_tracking.cpp
=> FOGL-7076:added check for update cache on count increase

tests/system/python/packages/test_authentication.py
=> FOGL-7119 authentication package based system tests updated & some indentation fixes

Makefile, docs/building_fledge/06_testing.rst, tests/README.rst, tests/system/python/README.rst, tests/system/python/iprpc/README.rst, tests/system/python/scripts/install_python_plugin
=> pip3 occurrences is replaced with python3 -m pip

docs/OMF.rst, docs/scripts/plugin_and_service_documentation
=> duplicate label & typo's fixes for inbuilt OMF plugin

python/fledge/services/core/api/task.py, tests/unit/python/fledge/services/core/api/test_task.py
=> FOGL-7244 Add task API always with C process name

C/common/config_category.cpp, C/common/include/config_category.h
=> FOGL-7138 Fix for missing configuration item properties

C/plugins/north/OMF/linkdata.cpp
Please build on a stretch platform, I don't have one.
=> FOGL-7265 Add include of typeinfo

tests/unit/C/plugins/storage/common/CMakeLists.txt, tests/unit/C/plugins/storage/postgres/CMakeLists.txt, tests/unit/C/plugins/storage/sqlite/CMakeLists.txt, tests/unit/C/plugins/storage/sqlitelb/CMakeLists.txt, tests/unit/C/plugins/storage/sqlitememory/CMakeLists.txt, tests/unit/C/services/storage/postgres/CMakeLists.txt, tests/unit/C/services/storage/postgres/plugins/common/CMakeLists.txt
Signed-off-by: nandan <nandan.ghildiyal@gmail.com>
=> FOGL-7221: Updated CMakeLists.txt file to generate correct link.txt file

C/plugins/north/OMF/plugin.cpp
=> FOGL-7288 Populate version in all cases to get correct OMF version set

scripts/plugins/storage/sqlitelb/init.sql
=> Add missing packages table to init.sql

C/plugins/north/OMF/linkdata.cpp, tests/system/lab/test, tests/system/python/conftest.py, tests/system/python/packages/test_multiple_assets.py, tests/system/python/packages/test_omf_naming_scheme.py, tests/system/python/packages/test_omf_north_service.py, tests/system/python/packages/test_pi_webapi.py, tests/system/python/pair/test_c_north_service_pair.py, tests/system/python/pair/test_pyton_north_service_pair.py
Signed-off-by: Mohit Tomar <m.singh19994@gmail.com>
=> FOGL-7285 System tests for PIWebAPI are failing with PIWebAPI 2021 sp2.

tests/system/python/conftest.py
Testing notes are available on FOGL-7332 JIRA itself
=> FOGL-7332 removed PYTHONPATH dependency and added some utility methods in conftest file

python/fledge/services/core/api/repos/configure.py, tests/system/python/scripts/install_c_plugin, tests/system/python/scripts/install_c_service, tests/system/python/scripts/package/setup
=> FOGL-7260 (pending items) + FOGL-7322

extras/scripts/fledge.service
=> FOGL-7257 fledge start/stop as service without sudo on CentOS Stream9

C/common/config_category.cpp
=> FOGL-7366 remove duplication of options

C/services/storage/configuration.cpp
=> FOGL-7371 Set value of readingPlugin to default if empty

C/services/storage/configuration.cpp
=> Fix memory allocation error

C/common/include/reading.h, C/common/reading.cpp
=> FOGL-7376 Add the ability to create a reading using a JSON document to

C/common/reading.cpp
=> FOGL-7385: Fix in TZ string processing

tests/system/python/api/test_notification.py, tests/system/python/e2e/test_e2e_notification_service_with_plugins.py, tests/system/python/scripts/install_c_plugin
Custom CI-run - `fledge_nightly_build_ubuntu18_aarch64/39/console`
=> FOGL-7401 notification system tests updated as per new changes in notification service

C/services/south/include/ingest.h, C/services/south/ingest.cpp, C/services/south/south.cpp
=> FOGL-7518 Empty statistics entry is created incorrectly when stats are

C/services/storage/include/storage_registry.h, C/services/storage/storage_registry.cpp
Added a mutex to protect reads/writes to m_registrations vector.
=> FOGL-7415: Fix a storage service crash when Notification instance is disabled

python/fledge/common/plugin_discovery.py
**API response**
```
$ curl -sX GET localhost:8081/fledge/plugins/installed | jq
{
"plugins": [
{
"name": "http_north",
"type": "north",
"description": "HTTP North Plugin",
"version": "2.1.0-1-g5fd6325",
"installedDirectory": "north/http_north",
"packageName": "fledge-north-http-north"
},
{
"name": "OMF",
"type": "north",
"description": "PI Server North C Plugin",
"version": "2.1.0",
"installedDirectory": "north/OMF",
"packageName": ""
},
{
"name": "Benchmark",
"type": "south",
"description": "Simulated data generation for benchmark tests",
"version": "2.1.0-4-gf2a92fb",
"installedDirectory": "south/Benchmark",
"packageName": "fledge-south-benchmark"
},
{
"name": "lathesim",
"type": "south",
"description": "A simulation of a lathe",
"version": "2.1.0-2-g9b1b348",
"installedDirectory": …
```
=> FOGL-7513 package Name for installed plugins from external .Package file if exists

python/fledge/services/core/api/browser.py
With single asset
```
// http://localhost:8081/fledge/asset/asset_1?seconds=100
[
{
"reading": {
"dp_1": -2
},
"timestamp": "2023-03-20 17:45:15.660630"
}
]
```
With multiple asset
```
// http://localhost:8081/fledge/asset/asset_1?seconds=600&additional=asset_2,testcard,http-asset_2
{
"asset_1": [
{
"reading": {
"dp_1": -2
},
"timestamp": "2023-03-20 17:45:15.660630"
}
],
"asset_2": [
{
"reading": {
"lux": 99311.197
},
"timestamp": "2023-03-20 17:45:15.660685"
}
],
"testcard": [
{
"reading": {
"testcard": "Data removed for brevity"
},
"timestamp": "2023-03-20 17:45:09.200858"
},
{
"reading": {
"testcard": "Data removed for brevity"
},
"timestamp": "2023-03-20 17:45:08.200915"
},
{
"reading": {
"testcard": "Data removed for brevity"
},
"timestamp": "2023-03-20 17:45:07.200874"
}
], …
```
=> FOGL-7554 Additional query parameter is added in asset graph API

tests/system/lab/README.rst, tests/system/lab/reset, tests/system/lab/run, tests/system/lab/run_until_fails, tests/system/lab/test.config
=> FOGL-7533_patch - Improvements for Lab Script

scripts/extras/update_task.apt
Only Debian based handling added
=> FOGL-7480 Fledge packages update API modified

VERSION, python/fledge/services/core/api/control_pipeline.py, python/fledge/services/core/routes.py, scripts/plugins/storage/postgres/downgrade/59.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/60.sql, scripts/plugins/storage/sqlite/downgrade/59.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/60.sql, scripts/plugins/storage/sqlitelb/downgrade/59.sql, scripts/plugins/storage/sqlitelb/init.sql, scripts/plugins/storage/sqlitelb/upgrade/60.sql
Control filter Pipeline API
Note:
There are some TODO's comments as pending queries on the original doc itself. So far API has all stuff IN; pending items may be handled separately
**Curl Sample Output**
```
$ curl -sX GET http://localhost:8081/fledge/control/lookup | jq
{
"controlLookup": {
"source": [
{
"cpsid": 1,
"name": "Any",
"description": "Any source."
},
{
"cpsid": 2,
"name": "Service",
"description": "A named service in source of the control pipeline."
},
{
"cpsid": 3,
"name": "API",
"description": "The control pipeline source is the REST API."
},
{
"cpsid": 4,
"name": "Notification",
"description": "The control pipeline originated from a notification."
},
{
"cpsid": 5,
"name": "Schedule",
"description": "The control request was triggered by a schedule."
},
{
"cpsid": 6,
"name": …
```
=> FOGL-7577 - API for Control filter pipelines

C/services/common/service_security.cpp
FOGL-7670: call refresh token two minutes before expiration
=> FOGL-7670: call refresh token two minutes before expiration

VERSION, scripts/plugins/storage/postgres/downgrade/60.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/61.sql, scripts/plugins/storage/sqlite/downgrade/60.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/61.sql, scripts/plugins/storage/sqlitelb/downgrade/60.sql, scripts/plugins/storage/sqlitelb/init.sql, scripts/plugins/storage/sqlitelb/upgrade/61.sql, tests/system/python/api/test_audit.py
Support added for new audit log codes for User operations
`'USRAD', 'USRDL', 'USRCH', 'USRRS'`
=> FOGL-7704 new audit log codes for User

C/common/reading.cpp, tests/unit/C/common/test_reading_array.cpp
Unit test case result : 
```
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from TESTReading
[ RUN      ] TESTReading.TestReadingForNestedListType
[       OK ] TESTReading.TestReadingForNestedListType (1 ms)
[ RUN      ] TESTReading.TestUnspportedReadingForListType
[       OK ] TESTReading.TestUnspportedReadingForListType (3 ms)
[ RUN      ] TESTReading.TestReadingForListType
[       OK ] TESTReading.TestReadingForListType (2 ms)
[----------] 3 tests from TESTReading (8 ms total)
[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (11 ms total)
[  PASSED  ] 3 tests.
```
=> FOGL-7748: Added support for JSONArray type in Reading class

C/common/asset_tracking.cpp, C/common/include/asset_tracking.h, C/common/include/management_client.h, C/common/management_client.cpp, C/services/south/include/ingest.h, C/services/south/ingest.cpp
FOGL-7835: reduce asset tracking calls in ingest class
=> FOGL-7835: reduce asset tracking calls in ingest class

python/fledge/services/core/api/plugins/remove.py, python/fledge/services/core/api/plugins/update.py
Similar issue was fixed with https://github.com/fledge-iot/fledge/pull/994
=> FOGL-7860 Fix Caching endpoint address scheme of core management API used by Package management API

C/services/south/include/south_plugin.h, C/services/south/south_plugin.cpp
FOGL-7886: pospone write and operation calls for async plugins
=> FOGL-7886: pospone write and operation calls for async plugins

python/fledge/services/core/support.py, scripts/common/get_logs.sh
Also updated the support bundle for the syslog utility files as well. So that it will help us in debugging if anything break.
=> FOGL-7852 improvements in syslog utility script

C/services/north/data_send.cpp
- Added TODO for improvment while calling plugin_send.
- Updated comment for memory leak fix.
=> FOGL-7862.patch

C/services/north/include/north_service.h, C/services/north/north.cpp
service
Used by control dispatcher when matching source for control pipelines
=> FOGL-7658 Add source information for control requests from the north

C/common/pythonreading.cpp
Custom system tests CI JOB ran against Ub20 and as such no regression found. But we can try with nested branch of sinusoid https://github.com/fledge-iot/fledge-south-sinusoid/pull/30
=> FOGL-7822 Handling for nested objects in python readings interface

C/plugins/storage/sqlite/common/readings.cpp, C/plugins/storage/sqlitelb/common/readings.cpp, python/fledge/common/storage_client/payload_builder.py, tests/unit/python/fledge/common/storage_client/data/payload_select_alias_with_timezone.json, tests/unit/python/fledge/common/storage_client/test_payload_builder.py, tests/unit/python/fledge/services/core/api/test_browser_assets.py
UTC always with Sqlite Plugins on readings!
As per CI Jobs - unit & system test health is good on both Sqlite & PostgreSql
=> FOGL-7696 Addition of UTC timezone to the python payload builder & also Sqlite plugins readings has with UTC instead of localtime

python/fledge/services/core/api/control_service/pipeline.py
Mentioned problem in ticket should be resolved by the change.
More refinements will be done in FOGL-7913 as per discussion.
=> FOGL-7927 control pipeline filters fixes on CRUD's along maintained its order

docs/control.rst, docs/scripts/fledge_plugin_list, docs/scripts/plugin_and_service_documentation
Previously inbuilt plugin entry was not in an alphabetical order.
And with the given change it actually now in alphabetically order with all plugins.
Custom RTD link's are given below 
a) https://fledge-iot.readthedocs.io/en/fogl-5691/fledge_plugins.html
b) https://fledge-iot.readthedocs.io/en/fogl-5691/plugin_index.html
Also fixed the malformed table in control pipeline when white-labelled.
=> FOGL-5691 - Sorting of inbuilt plugin in alphabetically order for both plugins summary list and detailed documentation

python/fledge/services/core/support.py
Below are the tables added to support bundle
=> FOGL-7982 monitors and statistics content added into support bundle

C/plugins/storage/sqlite/common/connection.cpp, C/tasks/statistics_history/stats_history.cpp
=> FOGL-7983 Store statistic history in UTC and fix the newer/older

python/fledge/services/core/api/control_service/entrypoint.py, python/fledge/services/core/routes.py
Below are the Curl's
```
echo "POST: operation...."
curl -sX POST http://localhost:8081/fledge/control/manage -d '{"name": "FocusCamera", "description": "Perform focus operation in camera", "type": "operation", "destination": "broadcast", "operation_name": "focus", "constants": {"units" : "m"}, "variables": {"distance": "92"}, "anonymous": true, "allow": []}' | jq
echo "POST: write...."
curl -sX POST http://localhost:8081/fledge/control/manage -d '{"name": "Set lathe Speed", "description": "Set the speed of the lathe", "type": "write", "destination": "asset", "asset": "spin", "constants": {"units" : "cm"}, "variables": {"distance": "100"}, "anonymous": false, "allow": ["admin", "control"]}' | jq
echo "GET ALL...."
curl -sX GET http://localhost:8081/fledge/control/manage | jq
echo "GET By …
```
=> FOGL-7985 Control Flow API

python/fledge/plugins/storage/common/lib.py, python/fledge/services/core/api/package_log.py, python/fledge/services/core/api/plugins/common.py, python/fledge/services/core/support.py
=> FOGL-6083 UTC timezone in API for backup, package log

python/fledge/common/web/middleware.py, python/fledge/services/core/api/control_service/entrypoint.py
Mentioned problem which were raised in FOGL-8066 has fixed with the given change though added TODO comments in the code and should get resolved via FOGL-8037 after clarification
=> Control update request condition removed from middleware and to allow or reject validation in its handler 

python/fledge/services/core/api/control_service/entrypoint.py
Both POST and PUT entrypoint should be good for **allow** KV pair along with validation of user list.
GET should also return correct info of allowed list
**Given changes only handles the allow user**
=> user column handling added in control_api_acl table when using entrypoint PUT API

scripts/services/north_C
=> FOGL-8122 Remove stray character in north_c script that prevented

python/fledge/services/core/api/control_service/entrypoint.py, tests/unit/python/fledge/services/core/api/control_service/test_entrypoint.py
Here is the Coverage Report
```
Module | statements | missing | excluded | coverage
---------------------------------------------------------------------------------------------------------------------------
python/fledge/services/core/api/control_service/entrypoint.py | 436 | 115 | 0 | 74%
```
=> FOGL-8038 Control Flow entrypoint unit tests added

tests/system/python/api/control_service/test_entrypoint.py
Custom Job ran over `fledge_nightly_build_ub2004/1038` and newly API tests are passing.
=> FOGL-8138 Control Flow entrypoint API system tests added

scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlitelb/init.sql
as there are no upgrade/downgrade implicaitons in this change
=> FOGL-8120 Update default purge schedule. Note there is no schema change

tests/unit/python/fledge/tasks/purge/test_purge.py
As purge tests were too old and some assert statements are NOT good. So fixed that and cover more coverage when we have both Age And Size with purge and retain flag in the configuration set.
=> purge tests fixes and updated as per FOGL-8166

C/plugins/storage/postgres/connection.cpp, python/fledge/services/core/api/statistics.py
FOGL-8087: fix for statistics rate in Postgres
Also fixes FOGL-4102
Note: FOGL-7960 should be fixed as well
=> FOGL-8087: fix for statistics rate in Postgres

C/plugins/storage/postgres/connection.cpp, python/fledge/services/core/api/statistics.py
Reverts fledge-iot/fledge#1187
=> Revert "FOGL-8087: fix for statistics rate in Postgres"

C/common/logger.cpp, C/plugins/north/OMF/include/linkedlookup.h, C/plugins/north/OMF/include/omf.h, C/plugins/north/OMF/include/omfinfo.h, C/plugins/north/OMF/include/omflinkeddata.h, C/plugins/north/OMF/linkdata.cpp, C/plugins/north/OMF/omf.cpp, C/plugins/north/OMF/omfinfo.cpp, Makefile, scripts/services/north_C
Combine the lookup tables to reduce the memory requirement when using a large number of tags
=> FOGL-8185 Combine lookup information

C/plugins/storage/sqlite/common/connection.cpp, C/services/north/data_load.cpp
=> FOGL-8222 Improve error and warning reporting when updates and inserts

python/fledge/services/core/api/performance_monitor.py, python/fledge/services/core/routes.py
DOC Pending queries resolved with FOGL-8275
=> FOGL-8167 Performance Counters API addition

tests/system/python/packages/test_north_pi_webapi_nw_throttle.py, tests/system/python/packages/test_rule_data_availability.py
Below the jobs that are fixed after changes of this PR:
1. http://jenkins.dianomic.com:8080/view/PI%20stuff/job/fledge_packages_system_test_north_pi_webapi_nw_throttle_piwebapi2021sp2/296/
2. http://jenkins.dianomic.com:8080/job/fledge_packages_system_test_data_availability_notification_rule/80/
=> System test fixes

python/fledge/services/core/proxy.py
FOGL-8263: return raw data for bucket/id request
=> FOGL-8263: return raw data for bucket/id request

C/plugins/storage/postgres/connection.cpp
FOGL-8282: now() is the only supported function in postgres plugin
=> FOGL-8282: now() is the only supported function in postgres plugin

C/common/reading_set.cpp
FOGL-8321: Fix for large value of reading id
=> FOGL-8321: Fix for large value of reading id

C/common/result_set.cpp
=> FOGL-8353 Resolve issue if first row in a columns contains the string

python/fledge/common/alert_manager.py, python/fledge/common/microservice_management_client/microservice_management_client.py, python/fledge/services/common/microservice_management/routes.py, python/fledge/services/core/server.py, tests/system/python/packages/test_available_and_install_api.py
=> FOGL-8440 Alert Management routes added and also Python based Management Client updated to provide an interface to these routes

VERSION, docs/plugin_developers_guide/02_writing_plugins.rst, python/fledge/common/alert_manager.py, python/fledge/services/core/api/alerts.py, python/fledge/services/core/api/common.py, python/fledge/services/core/routes.py, python/fledge/services/core/server.py, scripts/plugins/storage/postgres/downgrade/67.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/68.sql, scripts/plugins/storage/sqlite/downgrade/67.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/68.sql, scripts/plugins/storage/sqlitelb/downgrade/67.sql, scripts/plugins/storage/sqlitelb/init.sql, scripts/plugins/storage/sqlitelb/upgrade/68.sql, tests/system/python/api/test_common.py, tests/unit/python/fledge/services/core/api/test_common_ping.py
=> FOGL-8439 Alerts feature

python/fledge/services/core/api/service.py, python/fledge/services/core/service_registry/monitor.py
Below is the sample output 
```
{
"alerts": [
{
"key": "NotificationServer",
"message": "The Service NotificationServer restarted 1 times",
"urgency": "Normal",
"timestamp": "2024-02-09 09:54:48.384"
}
{
"key": "S #123",
"message": "The Service S #123 restarted 4 times",
"urgency": "Normal",
"timestamp": "2024-02-09 09:58:47.383"
}
]
}
```
=> FOGL-8444 alert raised on restarting a service

docs/control.rst
=> FOGL-8525 Fix type for service in control pipeline source/destination

C/common/management_client.cpp, C/common/reading_set.cpp
=> FOGL-8554 Fix issue if a configuration category has an item called

C/common/config_category.cpp
=> FOGL-8618 Add values and default when converting values and defaults to

python/fledge/services/core/server.py
Fixes [issue](https://github.com/fledge-iot/fledge/issues/1310)
=> FOGL-8610 last_object reset in streams fixes when readings stored in memory on restart

C/services/common/include/perfmonitors.h, C/services/common/perfmonitor.cpp, C/services/storage/configuration.cpp, C/services/storage/include/storage_api.h, C/services/storage/include/storage_plugin.h, C/services/storage/storage.cpp, C/services/storage/storage_api.cpp, docs/plugin_developers_guide/04_north_plugins.rst
FOGL-8607: initial implementation
=> FOGL-8607: Add performance monitors to the storage engine

python/fledge/services/core/api/control_service/pipeline.py, tests/unit/python/fledge/services/core/api/control_service/test_pipeline.py
=> FOGL-7737 Control Pipeline API unit tests along with filters 

VERSION, python/fledge/common/service_record.py, python/fledge/services/core/api/service.py, python/fledge/services/core/scheduler/scheduler.py, scripts/fledge, scripts/plugins/storage/postgres/downgrade/70.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/71.sql, scripts/plugins/storage/sqlite/downgrade/70.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/71.sql, scripts/plugins/storage/sqlitelb/downgrade/70.sql, scripts/plugins/storage/sqlitelb/init.sql, scripts/plugins/storage/sqlitelb/upgrade/71.sql, scripts/services/pipeline_c, tests/unit/python/fledge/common/test_service_record.py, tests/unit/python/fledge/services/core/api/test_service.py
As we move further we will support and fix more areas
Note:
Integration testing only once FOGL-8461 is ready!
=> FOGL-8671 Initial implementation for Pipeline type service support at python Core side

C/plugins/storage/sqlite/common/connection.cpp, C/plugins/storage/sqlitelb/common/connection.cpp
FOGL-8533: fix for "null" string value in mapResultSet
=> FOGL-8533: fix for "null" string value in mapResultSet

C/common/json_utils.cpp, tests/unit/C/common/test_json_utils.cpp
=> FOGL-8626: fix double quotes JSON parsing

tests/unit/python/fledge/common/web/test_ssl_wrapper.py
Verified on - Ubuntu, Raspberry and CentOS Stream 9
=> FOGL-8675 SSL verifier based cert check unit tests fixes as per OPENSSL version 

C/services/common/include/plugin_manager.h, C/services/common/plugin_manager.cpp
- Added an extension to find plugins matching type and plugin flags.
=> FOGL-8634: Plugin Manager Upgrade

C/services/north/north.cpp, C/services/south/south.cpp, C/services/storage/storage.cpp
- Updated profile directory to FLEDGE_DATA.
=> FOGL-8739: Profile builds for each service.

C/services/north/data_send.cpp
=> FOGL-8787: change log message

requirements.sh
=> Use SQLite 3.45.3

requirements.sh
FOGL-8793: use sqlite3-pkg repo main branch
=> FOGL-8793: use sqlite3-pkg repo main branch

docs/securing_fledge.rst
Note, we will need to do a further update following completion of FOGL-8757
=> FOGL-8761 Update security Fledge section of documentation

C/services/north/data_send.cpp, VERSION, scripts/plugins/storage/postgres/downgrade/72.sql, scripts/plugins/storage/postgres/upgrade/73.sql, scripts/plugins/storage/sqlite/downgrade/72.sql, scripts/plugins/storage/sqlite/upgrade/73.sql, scripts/plugins/storage/sqlitelb/downgrade/72.sql, scripts/plugins/storage/sqlitelb/upgrade/73.sql
Due to schema update order this can not be checked in until after FOGL-8753
=> FOGL-8851 Fix typo in statistics description

C/services/north/data_load.cpp
- Reverting changes done in FOGL-8285.
=> FOGL-8913: Fix readings count getting doubled on restart.

C/services/north/data_load.cpp
- Updated last sent id if no readings to send.
=> FOGL-8947: Last send Id not updated for single send cycle.

C/services/north/data_send.cpp
FOGL-8955: fix check of updateTable return value
=> FOGL-8955: fix check of updateTable return value

C/common/filter_pipeline.cpp, C/common/include/pipeline_element.h, C/services/north/data_send.cpp, C/services/north/include/data_sender.h, C/services/south/south.cpp
to load south plugins. Also tidyup some compiler warnings
=> FOGL-8591 Improve handling of exceptions in pipeline creation and failure

C/common/filter_pipeline.cpp, C/services/south/ingest.cpp
=> FOGL-9027 Resolve issue with Python filters sending data during

docs/quick_start/north.rst
See the note directive breaks - https://fledge-iot.readthedocs.io/en/develop/quick_start/north.html
And with the given fix this will be fixed
=> DOC fixes for FOGL-9029 changes

tests/system/python/packages/test_rule_data_availability.py
I ran the following job on the latest commit(530d9ed15f401154006add2df688cf9ef8631120) of this pullrequest:
http://jenkins.dianomic.com:8080/job/fledge_packages_system_test_data_availability_notification_rule/163/
=> Added Pytest xfail marker for FOGL-7712

python/requirements-test.txt, tests/system/python/api/test_alerts.py, tests/system/python/api/test_audit.py, tests/system/python/api/test_browser_assets.py, tests/system/python/api/test_statistics.py, tests/system/python/helpers/utils.py
Ran CI custom Job here - 
Ub20+Sqlite `fledge_on_demand_code_coverage_ub2004/53/`
Ub18 + PostgreSQL - `Fledge%20Custom%20Jobs/job/fledge_postgres_ub1804/831/`
=> FOGL-8796 validate timestamp in API tests

C/plugins/storage/common/disk_monitor.cpp, C/plugins/storage/common/include/disk_monitor.h
an issue accessing the filesystem status
=> FOGL-9091 Improve error reporting and rate limit error logs when we have

C/common/config_category.cpp, tests/unit/C/common/test_config_category.cpp, tests/unit/C/common/test_default_config_category.cpp
FOGL-9143: remove "\n" string from JSON object converted from string
=> FOGL-9143: remove "\n" string from JSON object

tests/system/python/api/test_browser_assets.py
Custom build ran - `fledge_on_demand_code_coverage_ub2004/84/` and it passes.
=> FOGL-9229 DST fixes in browser API integration tests

C/common/reading.cpp, tests/unit/C/common/test_reading.cpp
length of default into account
=> FOGL-9251 Fix issue with defaults in macro substitution not taking

python/fledge/common/configuration_manager.py, tests/unit/python/fledge/common/test_configuration_manager.py
Existing system tests have no impact with the given change
=> FOGL-9144 - Duplicate entries handling in configuration list type with item object

python/fledge/common/utils.py, python/fledge/services/common/utils.py, python/fledge/services/core/server.py, tests/unit/python/fledge/services/common/test_services_common_utils.py, tests/unit/python/fledge/services/core/test_server.py
=> FOGL-9336 Fixes for the loop argument in asyncio.sleep() across different Python versions

tests/system/python/packages/test_omf_north_service.py
Custom CI run `fledge_packages_system_test_north_service_ub1804/684` and now passed.
=> Fixes for filter verification in OMF North service with system tests for filters as per FOGL-6256

C/common/pipeline_filter.cpp
=> FOGL-9540 Correct key name used when persisting data in pipeline element

C/common/include/plugin_data.h, C/common/pipeline_filter.cpp, C/common/plugin_data.cpp, C/services/north/north.cpp, C/services/south/south.cpp, C/tasks/north/sending_process/sending.cpp, VERSION, python/fledge/services/core/api/filters.py, python/fledge/services/core/api/plugins/data.py, python/fledge/services/core/api/service.py, scripts/plugins/storage/postgres/downgrade/74.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/75.sql, scripts/plugins/storage/sqlite/downgrade/74.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/75.sql, scripts/plugins/storage/sqlitelb/downgrade/74.sql, scripts/plugins/storage/sqlitelb/init.sql, scripts/plugins/storage/sqlitelb/upgrade/75.sql, tests/unit/python/fledge/services/core/api/test_filters.py
=> FOGL-9458 Plugin data fixes are needed for filters, especially with the new schema

docs/storage.rst
Updated document about Connect Fledge with remote postgres database server
=> FOGL-7666 Updated document for configuration of Fledge connection with remote postgres database server 

VERSION, python/fledge/common/web/middleware.py, python/fledge/services/core/api/auth.py, python/fledge/services/core/api/certificate_store.py, scripts/fledge, scripts/plugins/storage/postgres/downgrade/75.sql, scripts/plugins/storage/postgres/init.sql, scripts/plugins/storage/postgres/upgrade/76.sql, scripts/plugins/storage/sqlite/downgrade/75.sql, scripts/plugins/storage/sqlite/init.sql, scripts/plugins/storage/sqlite/upgrade/76.sql, scripts/plugins/storage/sqlitelb/downgrade/75.sql, scripts/plugins/storage/sqlitelb/init.sql, scripts/plugins/storage/sqlitelb/upgrade/76.sql, tests/system/python/api/test_authentication.py, tests/system/python/api/test_endpoints_with_different_user_types.py, tests/system/python/api/test_passwords.py, tests/system/python/packages/test_authentication.py
Incorporation of the Systemctl role into the user roles table, along with the user's responsibility to utilize a minimal set of entry points required to execute the various commands invoked by the Fledge script.
=> FOGL-9651 Incorporation of the Systemctl role into the user roles table

python/fledge/services/core/api/configuration.py, tests/system/python/api/test_common.py, tests/system/python/api/test_endpoints_with_different_user_types.py, tests/system/python/api/test_passwords.py, tests/system/python/api/test_service.py, tests/system/python/conftest.py, tests/system/python/e2e/test_e2e_coap_OCS.py
Ub24 - `fledge_test_coverage_on_demand/260/#showFailuresLink`
=> FOGL-9820 Python tests fixes
